import type { Lang } from "@/lib/locale";

const zh = {
  workspace: "我的 Choice", myWorks: "我的作品 / 收藏", publicChoice: "公開 Choice", issue: "Choice 期數", chooseIssue: "選擇 Choice 期數", newIssue: "新增一期", untitled: "未命名 Choice", published: "已發布", draft: "草稿", selection: "Choice 選曲", source: "選曲來源", favorites: "收藏歌曲", selected: "已選", editIssue: "編輯本期 Choice", search: "搜尋收藏歌曲", searchPlaceholder: "歌名 / 創作者", genre: "歌曲類型", allGenres: "所有類型", play: "播放試聽", unavailable: "目前無法公開播放", checkSong: "Choice 選曲", emptyFiltered: "沒有符合條件的歌曲。", emptySelected: "尚未選曲。", emptyFavorites: "目前沒有公開可播放的收藏歌曲。", editor: "本期 Choice", edit: "編輯", preview: "預覽", week: "週次（星期一）", title: "標題", intro: "推薦簡介", coverPreview: "Choice 封面預覽", cover: "封面", removeCover: "移除封面", saveUpdate: "儲存更新", saveDraft: "儲存草稿", busy: "處理中", publish: "發布 Choice", withdraw: "撤回發布", order: "播放順序", playAll: "全部試聽", up: "上移", down: "下移", remove: "移出 Choice", publicPage: "公開頁", copyLink: "複製公開連結", deleteIssue: "刪除這一期", confirmDelete: "確定刪除「{title}」？歌曲本身不會刪除。", loading: "正在準備你的 Choice...", schema: "Choice 資料尚未準備完成。", login: "請先登入。", failed: "Choice 操作失敗，請重試。", loadFailed: "無法讀取自己的 Choice。", createFailed: "無法建立草稿。", coverInvalid: "封面限 JPG、PNG、WebP、GIF，最大 10MB。", coverFailed: "封面上傳失敗，請重試。", saved: "Choice 已儲存。", selectionSaved: "Choice 選曲已儲存。", orderSaved: "播放順序已儲存。", withdrawn: "Choice 已撤回。", publishSuccess: "Choice 已發布。", coverRemoved: "封面已移除。", copied: "公開連結已複製。", copyFailed: "無法複製連結。", deleted: "這一期 Choice 已刪除。", saveFailed: "草稿同步失敗，請按儲存草稿重試。", readyCount: "可發布：{count} 首。", needCount: "還需 {count} 首才能發布。", maxCount: "每期最多 10 首。", notPublic: "歌單包含無法公開播放的作品，請先替換。", notFavorite: "只能加入自己已收藏且目前公開可播放的歌曲。", invalidWeek: "週次必須是星期一。", weekConflict: "這週已有 Choice，或歌單已更新。請重新載入。", minimumPublished: "已發布歌單至少保留 5 首，請先撤回再移除。", noItem: "找不到這份 Choice 或歌曲。", retry: "重新載入", syncing: "草稿同步中", unsaved: "尚未儲存", synced: "草稿已同步",
};
type Copy = Record<keyof typeof zh, string>;
const en: Copy = {
  workspace: "My Choice", myWorks: "My Works / Favorites", publicChoice: "Public Choices", issue: "Choice issues", chooseIssue: "Choose an issue", newIssue: "New issue", untitled: "Untitled Choice", published: "Published", draft: "Draft", selection: "Choice selection", source: "Selection source", favorites: "Favorites", selected: "Selected", editIssue: "Edit this Choice", search: "Search favorites", searchPlaceholder: "Song / Creator", genre: "Genre", allGenres: "All genres", play: "Preview track", unavailable: "Not publicly playable", checkSong: "Select for Choice", emptyFiltered: "No matching songs.", emptySelected: "No songs selected.", emptyFavorites: "No public playable favorites yet.", editor: "This Choice", edit: "Edit", preview: "Preview", week: "Week (Monday)", title: "Title", intro: "Introduction", coverPreview: "Choice cover preview", cover: "Cover", removeCover: "Remove cover", saveUpdate: "Save changes", saveDraft: "Save draft", busy: "Working", publish: "Publish Choice", withdraw: "Unpublish", order: "Play order", playAll: "Preview all", up: "Move up", down: "Move down", remove: "Remove from Choice", publicPage: "Public page", copyLink: "Copy public link", deleteIssue: "Delete this issue", confirmDelete: "Delete \"{title}\"? The songs themselves will not be deleted.", loading: "Loading your Choice...", schema: "Choice is not available yet.", login: "Please sign in.", failed: "Choice action failed. Try again.", loadFailed: "Could not load your Choice.", createFailed: "Could not create a draft.", coverInvalid: "Use JPG, PNG, WebP or GIF, up to 10MB.", coverFailed: "Cover upload failed. Try again.", saved: "Choice saved.", selectionSaved: "Selection saved.", orderSaved: "Play order saved.", withdrawn: "Choice unpublished.", publishSuccess: "Choice published.", coverRemoved: "Cover removed.", copied: "Public link copied.", copyFailed: "Could not copy the link.", deleted: "Choice deleted.", saveFailed: "Draft sync failed. Use Save draft to retry.", readyCount: "Ready to publish: {count} songs.", needCount: "Add {count} more songs to publish.", maxCount: "Up to 10 songs per issue.", notPublic: "Replace unavailable songs before publishing.", notFavorite: "Only your public playable favorites can be added.", invalidWeek: "The week must start on Monday.", weekConflict: "This week already has a Choice, or the playlist changed. Reload to continue.", minimumPublished: "Published playlists need at least 5 songs. Unpublish before removing.", noItem: "Choice or song not found.", retry: "Reload", syncing: "Syncing draft", unsaved: "Unsaved changes", synced: "Draft synced",
};
const ja: Copy = {
  workspace: "マイ Choice", myWorks: "作品 / お気に入り", publicChoice: "公開 Choice", issue: "Choice 一覧", chooseIssue: "Choice を選択", newIssue: "新規作成", untitled: "無題の Choice", published: "公開済み", draft: "下書き", selection: "Choice 選曲", source: "選曲元", favorites: "お気に入り", selected: "選択済み", editIssue: "この Choice を編集", search: "お気に入りを検索", searchPlaceholder: "曲名 / クリエイター", genre: "ジャンル", allGenres: "すべてのジャンル", play: "試聴", unavailable: "現在公開再生できません", checkSong: "Choice に選択", emptyFiltered: "該当する曲がありません。", emptySelected: "曲が選択されていません。", emptyFavorites: "公開再生できるお気に入りの曲がありません。", editor: "今回の Choice", edit: "編集", preview: "プレビュー", week: "週（月曜日）", title: "タイトル", intro: "紹介文", coverPreview: "Choice カバーのプレビュー", cover: "カバー", removeCover: "カバーを削除", saveUpdate: "変更を保存", saveDraft: "下書きを保存", busy: "処理中", publish: "Choice を公開", withdraw: "公開を取り消す", order: "再生順", playAll: "すべて試聴", up: "上へ", down: "下へ", remove: "Choice から外す", publicPage: "公開ページ", copyLink: "公開リンクをコピー", deleteIssue: "この Choice を削除", confirmDelete: "「{title}」を削除しますか？曲自体は削除されません。", loading: "Choice を読み込み中...", schema: "Choice はまだ利用できません。", login: "ログインしてください。", failed: "操作に失敗しました。もう一度お試しください。", loadFailed: "Choice を読み込めませんでした。", createFailed: "下書きを作成できませんでした。", coverInvalid: "JPG、PNG、WebP、GIF（最大 10MB）を選択してください。", coverFailed: "カバーのアップロードに失敗しました。", saved: "Choice を保存しました。", selectionSaved: "選曲を保存しました。", orderSaved: "再生順を保存しました。", withdrawn: "公開を取り消しました。", publishSuccess: "Choice を公開しました。", coverRemoved: "カバーを削除しました。", copied: "公開リンクをコピーしました。", copyFailed: "リンクをコピーできませんでした。", deleted: "Choice を削除しました。", saveFailed: "同期に失敗しました。「下書きを保存」で再試行してください。", readyCount: "公開可能：{count} 曲。", needCount: "公開まであと {count} 曲。", maxCount: "1 回につき最大 10 曲です。", notPublic: "公開再生できない曲を入れ替えてください。", notFavorite: "公開再生できるお気に入りの曲のみ追加できます。", invalidWeek: "週は月曜日を指定してください。", weekConflict: "この週の Choice は既に存在するか、更新されています。再読み込みしてください。", minimumPublished: "公開中は 5 曲以上が必要です。公開を取り消してから外してください。", noItem: "Choice または曲が見つかりません。", retry: "再読み込み", syncing: "下書きを同期中", unsaved: "未保存の変更", synced: "下書きを同期済み",
};
const ko: Copy = {
  workspace: "내 Choice", myWorks: "내 작품 / 즐겨찾기", publicChoice: "공개 Choice", issue: "Choice 목록", chooseIssue: "Choice 선택", newIssue: "새로 만들기", untitled: "제목 없는 Choice", published: "게시됨", draft: "초안", selection: "Choice 선곡", source: "선곡 목록", favorites: "즐겨찾기", selected: "선택됨", editIssue: "이 Choice 편집", search: "즐겨찾기 검색", searchPlaceholder: "곡명 / 크리에이터", genre: "장르", allGenres: "모든 장르", play: "미리 듣기", unavailable: "현재 공개 재생 불가", checkSong: "Choice에 선택", emptyFiltered: "일치하는 곡이 없습니다.", emptySelected: "선택한 곡이 없습니다.", emptyFavorites: "공개 재생 가능한 즐겨찾기 곡이 없습니다.", editor: "이번 Choice", edit: "편집", preview: "미리 보기", week: "주차 (월요일)", title: "제목", intro: "소개", coverPreview: "Choice 커버 미리 보기", cover: "커버", removeCover: "커버 삭제", saveUpdate: "변경 저장", saveDraft: "초안 저장", busy: "처리 중", publish: "Choice 게시", withdraw: "게시 취소", order: "재생 순서", playAll: "전체 미리 듣기", up: "위로", down: "아래로", remove: "Choice에서 제외", publicPage: "공개 페이지", copyLink: "공개 링크 복사", deleteIssue: "이 Choice 삭제", confirmDelete: "'{title}'을 삭제할까요? 곡 자체는 삭제되지 않습니다.", loading: "Choice 불러오는 중...", schema: "아직 Choice를 이용할 수 없습니다.", login: "로그인해 주세요.", failed: "작업에 실패했습니다. 다시 시도해 주세요.", loadFailed: "Choice를 불러오지 못했습니다.", createFailed: "초안을 만들지 못했습니다.", coverInvalid: "JPG, PNG, WebP, GIF 파일을 사용하세요 (최대 10MB).", coverFailed: "커버 업로드에 실패했습니다.", saved: "Choice가 저장되었습니다.", selectionSaved: "선곡이 저장되었습니다.", orderSaved: "재생 순서가 저장되었습니다.", withdrawn: "게시가 취소되었습니다.", publishSuccess: "Choice가 게시되었습니다.", coverRemoved: "커버가 삭제되었습니다.", copied: "공개 링크가 복사되었습니다.", copyFailed: "링크를 복사하지 못했습니다.", deleted: "Choice가 삭제되었습니다.", saveFailed: "초안 동기화에 실패했습니다. 초안 저장으로 다시 시도하세요.", readyCount: "게시 가능: {count}곡.", needCount: "게시하려면 {count}곡이 더 필요합니다.", maxCount: "한 회차에 최대 10곡입니다.", notPublic: "공개 재생할 수 없는 곡을 교체해 주세요.", notFavorite: "공개 재생 가능한 내 즐겨찾기 곡만 추가할 수 있습니다.", invalidWeek: "주차는 월요일로 지정해 주세요.", weekConflict: "이번 주 Choice가 이미 있거나 변경되었습니다. 다시 불러오세요.", minimumPublished: "게시된 목록에는 최소 5곡이 필요합니다. 먼저 게시를 취소하세요.", noItem: "Choice 또는 곡을 찾을 수 없습니다.", retry: "다시 불러오기", syncing: "초안 동기화 중", unsaved: "저장되지 않은 변경", synced: "초안 동기화됨",
};

export const creatorChoiceCopy: Record<Lang, Copy> = { zh, en, ja, ko };

export function creatorChoiceError(message: string | undefined, lang: Lang) {
  const copy = creatorChoiceCopy[lang];
  if (!message) return copy.failed;
  if (/星期一|週期/.test(message)) return copy.invalidWeek;
  if (/這週|23505|其他視窗/.test(message)) return copy.weekConflict;
  if (/已收藏/.test(message)) return copy.notFavorite;
  if (/至少保留/.test(message)) return copy.minimumPublished;
  if (/公開播放/.test(message)) return copy.notPublic;
  if (/最多 10/.test(message)) return copy.maxCount;
  if (/發布 Choice 需要/.test(message)) return copy.needCount.replace("{count}", "5-10");
  if (/找不到/.test(message)) return copy.noItem;
  if (/登入/.test(message)) return copy.login;
  if (/尚未準備/.test(message)) return copy.schema;
  return lang === "zh" ? message : copy.failed;
}
