// Derived from the user-supplied artist encyclopedia.
// Source prose is not reproduced: each entry is normalized into four broad sonic traits.
export const SUNO_ARTIST_DNA_RAW = [
  ["A Perfect Circle", 3, "Alt-rock", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Adele", 3, "Soulful pop", "powerful high-impact vocals", "piano / keyboard-led arrangement", "emotion-led storytelling"],
  ["Aerosmith", 3, "Classic rock", "textured raspy vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["AFI", 3, "Punk rock", "powerful high-impact vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Akon", 3, "2000s R&B", "smooth intimate vocals", "synth-driven production", "era-conscious retro character"],
  ["Alabama Shakes", 3, "Blues-rock", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Alan Jackson", 3, "Classic 90s country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Alice in Chains", 3, "Grunge", "harmony-focused vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Allman Brothers Band", 3, "Southern rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Amy Winehouse", 3, "Soul", "textured raspy vocals", "bass and groove focus", "era-conscious retro character"],
  ["Andrea Bocelli", 3, "Operatic pop", "powerful high-impact vocals", "orchestral / string layers", "emotion-led storytelling"],
  ["Andrew Bird", 3, "Indie folk", "expressive lead vocals", "orchestral / string layers", "distinctive song character"],
  ["Angélique Kidjo", 3, "Afro-pop", "powerful high-impact vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Animal Collective", 3, "Experimental indie", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Anita Baker", 3, "Smooth R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Annie Lennox", 3, "80s pop-rock", "female lead vocals", "synth-driven production", "distinctive song character"],
  ["Antonio Carlos Jobim", 3, "Bossa nova", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["Arcade Fire", 3, "Indie rock", "harmony-focused vocals", "orchestral / string layers", "uplifting high-energy arc"],
  ["Ashanti", 3, "2000s R&B", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Asking Alexandria", 3, "Metalcore", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Aaliyah", 4, "90s R&B", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Above & Beyond", 4, "Trance", "female lead vocals", "synth-driven production", "uplifting high-energy arc"],
  ["Acceptance", 4, "2000s emo-pop", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Adam Levine", 4, "Pop-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Adam Ant", 4, "80s new wave", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Admiral Twin", 4, "Indie pop-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Agnes Obel", 4, "Chamber pop", "female lead vocals", "piano / keyboard-led arrangement", "dreamy spacious atmosphere"],
  ["Air", 4, "French electronic", "instrumental / production-led", "synth-driven production", "dreamy spacious atmosphere"],
  ["Alabama", 4, "Country", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["Alexisonfire", 4, "Post-hardcore", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Alvvays", 4, "Indie pop", "female lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Amanda Shires", 4, "Americana", "female lead vocals", "orchestral / string layers", "emotion-led storytelling"],
  ["America", 4, "70s folk-rock", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["Amos Lee", 4, "Soulful folk", "male lead vocals", "organic acoustic instrumentation", "emotion-led storytelling"],
  ["Anderson Paak", 4, "Funk-soul", "textured raspy vocals", "bass and groove focus", "distinctive song character"],
  ["Andy Grammer", 4, "Pop", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Angus & Julia Stone", 4, "Indie folk", "harmony-focused vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["Anna Nalick", 4, "Pop-rock", "female lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Anne-Marie", 4, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Anouk", 4, "Rock-pop", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["B.B. King", 5, "Blues", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Babyface", 5, "90s R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Bad Company", 5, "Classic rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Band of Horses", 5, "Indie rock", "male lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Bananarama", 5, "80s pop", "female lead vocals", "synth-driven production", "distinctive song character"],
  ["Barbra Streisand", 5, "Pop vocals", "powerful high-impact vocals", "orchestral / string layers", "distinctive song character"],
  ["Barry White", 5, "Soul", "male lead vocals", "orchestral / string layers", "emotion-led storytelling"],
  ["Bastille", 5, "Indie pop", "male lead vocals", "synth-driven production", "uplifting high-energy arc"],
  ["BBMak", 5, "2000s pop-rock", "harmony-focused vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Beck", 5, "Alternative rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Belinda Carlisle", 5, "80s pop-rock", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Belle & Sebastian", 5, "Indie pop", "male lead vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["Ben E. King", 5, "Soul", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Bert Jansch", 5, "Folk", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Beth Hart", 5, "Blues-rock", "textured raspy vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Big Daddy Kane", 5, "Golden age hip-hop", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Big Sean", 5, "Hip-hop", "rhythmic rap delivery", "signature layered arrangement", "distinctive song character"],
  ["Bill Withers", 5, "Soul", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Billy Idol", 5, "80s rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Billy Joel", 5, "Pop-rock", "male lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Billy Ocean", 6, "80s R&B-pop", "smooth intimate vocals", "rhythm-forward percussion", "emotion-led storytelling"],
  ["Billy Ray Cyrus", 6, "Country", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Bing Crosby", 6, "Crooner", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Black Sabbath", 6, "Heavy metal", "powerful high-impact vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Blackstreet", 6, "90s R&B", "harmony-focused vocals", "rhythm-forward percussion", "emotion-led storytelling"],
  ["Blake Shelton", 6, "Country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Blind Faith", 6, "Classic rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Blind Lemon Jefferson", 6, "Delta blues", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Blink-182", 6, "Pop-punk", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Blondie", 6, "New wave", "female lead vocals", "synth-driven production", "distinctive song character"],
  ["Blood, Sweat & Tears", 6, "Jazz-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Blue Öyster Cult", 6, "Classic rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Blues Traveler", 6, "Jam rock", "harmony-focused vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Bo Diddley", 6, "Rock pioneer", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Bob Marley", 6, "Reggae", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Bonnie Raitt", 6, "Blues-rock", "female lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Booker T. & the M.G.’s", 6, "Soul", "instrumental / production-led", "bass and groove focus", "distinctive song character"],
  ["Boston", 6, "Classic rock", "powerful high-impact vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Boy George", 6, "80s pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Brad Paisley", 6, "Country", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Cameo", 7, "Funk", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Camila Cabello", 7, "Pop", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Canned Heat", 7, "Blues-rock", "harmony-focused vocals", "bass and groove focus", "distinctive song character"],
  ["Carly Rae Jepsen", 7, "Pop", "female lead vocals", "synth-driven production", "emotion-led storytelling"],
  ["Carly Simon", 7, "70s singer-songwriter", "female lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Carmen McRae", 7, "Jazz", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Carpenters", 7, "Soft pop", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Carter Family", 7, "Folk", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["Cat Power", 7, "Indie folk", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Cat Stevens", 7, "70s folk-rock", "male lead vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["Charlie Parker", 7, "Bebop jazz", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Charlie Rich", 7, "Country-pop", "smooth intimate vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Charlie Wilson", 7, "R&B", "powerful high-impact vocals", "bass and groove focus", "emotion-led storytelling"],
  ["Cheap Trick", 7, "Rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Cher", 7, "Pop icon", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Cher Lloyd", 7, "Pop", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Chevelle", 7, "Alt-metal", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Chic", 7, "Disco", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Chick Corea", 7, "Jazz fusion", "expressive lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Chris Brown", 7, "R&B-pop", "smooth intimate vocals", "rhythm-forward percussion", "emotion-led storytelling"],
  ["Chris Cornell", 8, "Rock", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Chris Isaak", 8, "Rockabilly-pop", "male lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Chris Rea", 8, "Soft rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Chris Tomlin", 8, "Contemporary Christian", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Chrissie Hynde", 8, "Rock", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Chuck Berry", 8, "Rock pioneer", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Ciara", 8, "2000s R&B", "female lead vocals", "rhythm-forward percussion", "era-conscious retro character"],
  ["Cigarettes After Sex", 8, "Dream pop", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Clairo", 8, "Indie pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Clarence Carter", 8, "Soul", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Cliff Richard", 8, "Pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Clint Black", 8, "Country", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Cloud Nothings", 8, "Indie rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Cocteau Twins", 8, "Dream pop", "female lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Colbie Caillat", 8, "Pop", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Cole Swindell", 8, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Collective Soul", 8, "90s alt-rock", "textured raspy vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Commodores", 8, "Funk-soul", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Conway Twitty", 8, "Country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Coolio", 8, "90s hip-hop", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["D’banj", 9, "Afropop", "male lead vocals", "rhythm-forward percussion", "uplifting high-energy arc"],
  ["D12", 9, "Hip-hop crew", "rhythmic rap delivery", "signature layered arrangement", "dark atmospheric mood"],
  ["Damian Marley", 9, "Reggae", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Dan Fogelberg", 9, "Soft rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Dan + Shay", 9, "Country-pop", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Daniel Caesar", 9, "R&B", "male lead vocals", "bass and groove focus", "dreamy spacious atmosphere"],
  ["Daniel Johnston", 9, "Lo-fi indie", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Danny Elfman", 9, "Soundtracks", "expressive lead vocals", "orchestral / string layers", "dark atmospheric mood"],
  ["Danny Gokey", 9, "Contemporary Christian", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Darius Rucker", 9, "Country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Darude", 9, "Trance", "instrumental / production-led", "synth-driven production", "era-conscious retro character"],
  ["Dave Brubeck", 9, "Jazz", "expressive lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Dave Matthews Band", 9, "Jam rock", "male lead vocals", "orchestral / string layers", "distinctive song character"],
  ["David Byrne", 9, "Art rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["David Lee Roth", 9, "Rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Dead Kennedys", 9, "Punk rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Death Cab for Cutie", 9, "Indie rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Deep Purple", 9, "Classic rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Def Leppard", 9, "80s rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Deftones", 9, "Alt-metal", "male lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Del Shannon", 10, "60s rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Demi Lovato", 10, "Pop", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Dennis Brown", 10, "Reggae", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Dennis Wilson", 10, "Rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Descendents", 10, "Punk rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Desmond Dekker", 10, "Ska", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Destiny’s Child", 10, "R&B-pop", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Diana Krall", 10, "Jazz", "female lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Diana Ross", 10, "Motown soul", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Dierks Bentley", 10, "Country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Dion", 10, "60s rock", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Dionne Warwick", 10, "Soul-pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Diplo", 10, "EDM", "expressive lead vocals", "rhythm-forward percussion", "uplifting high-energy arc"],
  ["Dire Straits", 10, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Disclosure", 10, "House", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Disturbed", 10, "Metal", "powerful high-impact vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Dizzy Gillespie", 10, "Bebop jazz", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["DMX", 10, "Hip-hop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Don McLean", 10, "Folk-rock", "male lead vocals", "guitar-led arrangement", "era-conscious retro character"],
  ["Donna Fargo", 10, "Country", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Earth, Wind & Fire", 11, "Funk-soul", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Echo & the Bunnymen", 11, "Post-punk", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Edie Brickell & New Bohemians", 11, "Folk-rock", "smooth intimate vocals", "guitar-led arrangement", "distinctive song character"],
  ["Edwin Starr", 11, "Soul", "powerful high-impact vocals", "bass and groove focus", "distinctive song character"],
  ["Eels", 11, "Indie rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Electric Light Orchestra", 11, "Symphonic rock", "harmony-focused vocals", "orchestral / string layers", "distinctive song character"],
  ["Elephant Man", 11, "Dancehall", "male lead vocals", "rhythm-forward percussion", "uplifting high-energy arc"],
  ["Ella Fitzgerald", 11, "Jazz", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Ellie Goulding", 11, "Pop", "smooth intimate vocals", "synth-driven production", "dreamy spacious atmosphere"],
  ["Elton John", 11, "Pop-rock", "male lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Elvis Costello", 11, "New wave", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Emeli Sandé", 11, "Soul-pop", "powerful high-impact vocals", "piano / keyboard-led arrangement", "uplifting high-energy arc"],
  ["En Vogue", 11, "R&B", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Enrique Iglesias", 11, "Latin pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Enya", 11, "New age", "harmony-focused vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Epica", 11, "Symphonic metal", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Eric B. & Rakim", 11, "Golden age hip-hop", "smooth intimate vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Ernest Tubb", 11, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Esperanza Spalding", 11, "Jazz fusion", "female lead vocals", "bass and groove focus", "distinctive song character"],
  ["Everclear", 11, "Alt-rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Fabolous", 12, "Hip-hop", "smooth intimate vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Faces", 12, "Rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Faith Evans", 12, "R&B", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Faith Hill", 12, "Country-pop", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Fatboy Slim", 12, "Big beat", "expressive lead vocals", "rhythm-forward percussion", "uplifting high-energy arc"],
  ["Fear Factory", 12, "Industrial metal", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Feist", 12, "Indie pop", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Fifth Harmony", 12, "Pop", "harmony-focused vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Filter", 12, "Alt-rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Fine Young Cannibals", 12, "Pop-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Finger Eleven", 12, "Alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Firehouse", 12, "90s glam rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Five Finger Death Punch", 12, "Metal", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Five for Fighting", 12, "Pop-rock", "male lead vocals", "piano / keyboard-led arrangement", "emotion-led storytelling"],
  ["Flash and the Pan", 12, "New wave", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["Florida Georgia Line", 12, "Country-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Flying Lotus", 12, "Electronic", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Foghat", 12, "Classic rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Fontaines D.C.", 12, "Post-punk", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Foo Fighters", 12, "Alt-rock", "powerful high-impact vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Foreigner", 12, "Classic rock", "powerful high-impact vocals", "piano / keyboard-led arrangement", "uplifting high-energy arc"],
  ["Gang of Four", 13, "Post-punk", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Garbage", 13, "Alt-rock", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Gavin DeGraw", 13, "Pop-rock", "male lead vocals", "piano / keyboard-led arrangement", "emotion-led storytelling"],
  ["Genesis", 13, "Prog-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["George Benson", 13, "Jazz-pop", "smooth intimate vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["George Jones", 13, "Country", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["George Thorogood", 13, "Blues-rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Gerald Levert", 13, "R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Gerry Rafferty", 13, "Soft rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Ghost", 13, "Heavy metal", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Giant Rooks", 13, "Indie rock", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Gil Scott-Heron", 13, "Jazz-poetry", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Gillian Welch", 13, "Americana", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Gin Blossoms", 13, "90s alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Ginuwine", 13, "90s R&B", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Girl Talk", 13, "Mashup", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Girls Aloud", 13, "Pop", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Gladys Knight & the Pips", 13, "Soul", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Glass Animals", 13, "Indie pop", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["Glen Campbell", 13, "Country-pop", "male lead vocals", "orchestral / string layers", "distinctive song character"],
  ["Gloria Gaynor", 13, "Disco", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Godsmack", 13, "Alt-metal", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Hall & Oates", 14, "Blue-eyed soul", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Halsey", 14, "Pop", "female lead vocals", "synth-driven production", "emotion-led storytelling"],
  ["Hank Williams", 14, "Country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Hank Williams Jr.", 14, "Country-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Hanson", 14, "Pop-rock", "harmony-focused vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Happy Mondays", 14, "Madchester", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Hardwell", 14, "EDM", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Harold Melvin & the Blue Notes", 14, "Soul", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Harris J", 14, "Pop", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Harry Belafonte", 14, "Calypso", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Heart", 14, "Rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Herbie Hancock", 14, "Jazz fusion", "expressive lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Herman’s Hermits", 14, "60s pop", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Hilary Duff", 14, "Pop", "female lead vocals", "rhythm-forward percussion", "era-conscious retro character"],
  ["Hole", 14, "Grunge", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Hootie & the Blowfish", 14, "Pop-rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Hooverphonic", 14, "Trip-hop", "female lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Hot Hot Heat", 14, "Indie rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Howlin’ Wolf", 14, "Blues", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Huey Lewis & the News", 14, "80s rock", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Hunter Hayes", 14, "Country-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Hurts", 14, "Synth-pop", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["I Monster", 15, "Electronic", "male lead vocals", "signature layered arrangement", "era-conscious retro character"],
  ["Iggy Azalea", 15, "Hip-hop", "rhythmic rap delivery", "rhythm-forward percussion", "distinctive song character"],
  ["Iggy Pop", 15, "Punk rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Il Divo", 15, "Classical crossover", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Il Volo", 15, "Operatic pop", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Imelda May", 15, "Rockabilly", "female lead vocals", "bass and groove focus", "era-conscious retro character"],
  ["India.Arie", 15, "Neo-soul", "smooth intimate vocals", "bass and groove focus", "uplifting high-energy arc"],
  ["Indigo Girls", 15, "Folk", "harmony-focused vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["INXS", 15, "Rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Interpol", 15, "Post-punk revival", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Iron & Wine", 15, "Indie folk", "male lead vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["Iron Maiden", 15, "Heavy metal", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Isaac Hayes", 15, "Soul", "male lead vocals", "orchestral / string layers", "dreamy spacious atmosphere"],
  ["Isley Brothers", 15, "Soul-funk", "smooth intimate vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Israel Houghton", 15, "Contemporary Christian", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["J. Ivy", 15, "Spoken word", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["IU", 15, "K-pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Ivan Lins", 15, "Brazilian MPB", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Ivy Queen", 15, "Reggaeton", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Izzy Stradlin", 15, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Izo FitzRoy", 15, "Soul", "textured raspy vocals", "bass and groove focus", "uplifting high-energy arc"],
  ["Izzet Altinmeşe", 15, "Turkish folk", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Jack White", 16, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Jackson Browne", 16, "Folk-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Jackie Wilson", 16, "Soul", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Jadakiss", 16, "Hip-hop", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Jaheim", 16, "R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Ja Rule", 16, "Hip-hop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Jake Bugg", 16, "Indie rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Jamiroquai", 16, "Funk", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["James Bay", 16, "Pop-rock", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["James Morrison", 16, "Pop-soul", "male lead vocals", "organic acoustic instrumentation", "emotion-led storytelling"],
  ["James Taylor", 16, "Folk-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Jamie Cullum", 16, "Jazz-pop", "smooth intimate vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Jane’s Addiction", 16, "Alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Janet Jackson", 16, "Pop", "female lead vocals", "bass and groove focus", "distinctive song character"],
  ["Japan", 16, "New wave", "male lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["Jason Aldean", 16, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Jay Rock", 16, "Hip-hop", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Jay Sean", 16, "Pop-R&B", "smooth intimate vocals", "rhythm-forward percussion", "emotion-led storytelling"],
  ["Jean-Luc Ponty", 16, "Jazz fusion", "instrumental / production-led", "orchestral / string layers", "distinctive song character"],
  ["Jeff Beck", 16, "Rock", "instrumental / production-led", "guitar-led arrangement", "distinctive song character"],
  ["Jeff Buckley", 16, "Alt-rock", "powerful high-impact vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Jeremih", 16, "R&B", "smooth intimate vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Kacey Musgraves", 17, "Country-pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Kaiser Chiefs", 17, "Indie rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Kali Uchis", 17, "Neo-soul", "female lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Kansas", 17, "Classic rock", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Kanye West", 17, "Hip-hop", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Karen Dalton", 17, "Folk-blues", "textured raspy vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Kasabian", 17, "Indie rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Kat Dahlia", 17, "Pop-R&B", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Katharine McPhee", 17, "Pop", "female lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["KC and the Sunshine Band", 17, "Disco-funk", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Keane", 17, "Piano-rock", "powerful high-impact vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Keith Urban", 17, "Country-pop", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Kelis", 17, "R&B", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Kelly Clarkson", 17, "Pop-rock", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Kelly Rowland", 17, "R&B-pop", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Kenny Chesney", 17, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Kenny Loggins", 17, "Soft rock", "male lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Kenny Rogers", 17, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Kent", 17, "Indie rock", "male lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Kid Cudi", 17, "Hip-hop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Kid Rock", 17, "Rap-rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Killswitch Engage", 17, "Metalcore", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["La Roux", 18, "Synth-pop", "female lead vocals", "synth-driven production", "uplifting high-energy arc"],
  ["Labrinth", 18, "R&B-pop", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Lady A", 18, "Country-pop", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Lady Gaga", 18, "Pop", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Lana Del Rey", 18, "Indie pop", "female lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Lang Lang", 18, "Classical", "expressive lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Larry Graham", 18, "Funk", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Lauryn Hill", 18, "Neo-soul", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["LeAnn Rimes", 18, "Country-pop", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Lee Ann Womack", 18, "Country", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Leftfield", 18, "Electronic", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Lenny Kravitz", 18, "Rock", "male lead vocals", "bass and groove focus", "era-conscious retro character"],
  ["Leon Bridges", 18, "Soul", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Leonard Cohen", 18, "Folk-poet", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Leona Lewis", 18, "Pop", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Les Paul", 18, "Jazz guitar", "instrumental / production-led", "guitar-led arrangement", "distinctive song character"],
  ["Liam Gallagher", 18, "Rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Lifehouse", 18, "Pop-rock", "male lead vocals", "signature layered arrangement", "era-conscious retro character"],
  ["Lil Durk", 18, "Hip-hop", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Lil Jon", 18, "Crunk rap", "rhythmic rap delivery", "rhythm-forward percussion", "distinctive song character"],
  ["Lily Allen", 18, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Linda Ronstadt", 18, "Rock-country", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Lindsey Stirling", 19, "Electronic violin", "instrumental / production-led", "orchestral / string layers", "uplifting high-energy arc"],
  ["Lionel Richie", 19, "Pop-soul", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Little Big Town", 19, "Country", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Little Feat", 19, "Rock", "expressive lead vocals", "bass and groove focus", "distinctive song character"],
  ["Little Mix", 19, "Pop", "harmony-focused vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Liz Phair", 19, "Indie rock", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["LL Cool J", 19, "Hip-hop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Lloyd", 19, "R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["London Grammar", 19, "Indie pop", "female lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Loretta Lynn", 19, "Country", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Lou Reed", 19, "Rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Louis Armstrong", 19, "Jazz", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Louis Tomlinson", 19, "Pop", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Love", 19, "Psychedelic rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Lucinda Williams", 19, "Americana", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Ludacris", 19, "Hip-hop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Luke Bryan", 19, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Luke Combs", 19, "Country", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Luther Vandross", 19, "R&B-soul", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Lykke Li", 19, "Indie pop", "female lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Lynyrd Skynyrd", 19, "Southern rock", "textured raspy vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Lzzy Hale", 19, "Hard rock", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Mac DeMarco", 20, "Indie rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Macy Gray", 20, "Soul-pop", "textured raspy vocals", "bass and groove focus", "distinctive song character"],
  ["Maddie & Tae", 20, "Country duo", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Madvillain", 20, "Hip-hop", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Magic!", 20, "Reggae-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Maggie Rogers", 20, "Indie pop", "female lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Major Lazer", 20, "EDM-dancehall", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Maluma", 20, "Latin pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Maná", 20, "Latin rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Manfred Mann", 20, "Rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Manic Street Preachers", 20, "Alt-rock", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Maren Morris", 20, "Country-pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Mariah Carey", 20, "Pop-R&B", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Marillion", 20, "Prog-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Mark Knopfler", 20, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Mark Ronson", 20, "Pop producer", "instrumental / production-led", "bass and groove focus", "era-conscious retro character"],
  ["Marlon Williams", 20, "Folk", "smooth intimate vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Martha Reeves & The Vandellas", 20, "Motown", "female lead vocals", "rhythm-forward percussion", "uplifting high-energy arc"],
  ["Martina McBride", 20, "Country", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Mary J. Blige", 20, "R&B", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Matchbox Twenty", 20, "Alt-rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Matt Redman", 20, "Worship", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Matisyahu", 21, "Reggae-rap", "rhythmic rap delivery", "rhythm-forward percussion", "distinctive song character"],
  ["Matt Nathanson", 21, "Pop-rock", "male lead vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["MC Hammer", 21, "Rap-pop", "rhythmic rap delivery", "signature layered arrangement", "uplifting high-energy arc"],
  ["Megadeth", 21, "Thrash metal", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Melanie", 21, "Folk-pop", "female lead vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["Melissa Etheridge", 21, "Rock", "textured raspy vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Men at Work", 21, "80s Rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["MercyMe", 21, "Christian pop", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Merle Haggard", 21, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Method Man", 21, "Hip-hop", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Metric", 21, "Indie rock", "female lead vocals", "synth-driven production", "uplifting high-energy arc"],
  ["MGMT", 21, "Psychedelic pop", "male lead vocals", "synth-driven production", "dreamy spacious atmosphere"],
  ["Michael Bolton", 21, "Soft rock", "textured raspy vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Michael Bublé", 21, "Jazz-pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Michelle Branch", 21, "Pop-rock", "female lead vocals", "organic acoustic instrumentation", "era-conscious retro character"],
  ["Midnight Oil", 21, "Rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Miguel", 21, "R&B", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Mike Oldfield", 21, "Prog-rock", "instrumental / production-led", "signature layered arrangement", "distinctive song character"],
  ["Mike Posner", 21, "Pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Mika", 21, "Pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Minnie Riperton", 21, "Soul", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Miranda Lambert", 21, "Country", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Natalie Cole", 22, "Soul-pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Natalie Merchant", 22, "Folk-rock", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Natasha Bedingfield", 22, "Pop", "female lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Nate Dogg", 22, "Hip-hop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Nathaniel Rateliff & The Night Sweats", 22, "Soul-rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Naughty by Nature", 22, "Hip-hop", "expressive lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Nazareth", 22, "Hard rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Ne-Yo", 22, "R&B-pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Neko Case", 22, "Alt-country", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Neil Diamond", 22, "Pop-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Neil Finn", 22, "Indie-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Neil Young", 22, "Folk-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Nelly Furtado", 22, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Neneh Cherry", 22, "Trip-hop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Neutral Milk Hotel", 22, "Indie-folk", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["New Edition", 22, "R&B", "harmony-focused vocals", "bass and groove focus", "distinctive song character"],
  ["New Kids on the Block", 22, "Pop", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["New Order", 22, "Synth-pop", "male lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["Nick Cave & The Bad Seeds", 22, "Alt-rock", "male lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Nightwish", 22, "Symphonic metal", "powerful high-impact vocals", "orchestral / string layers", "distinctive song character"],
  ["Nine Inch Nails", 22, "Industrial rock", "male lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["No Doubt", 22, "Ska-pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["O.A.R.", 23, "Jam-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Of Monsters and Men", 23, "Indie-folk", "expressive lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Of Montreal", 23, "Indie-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["OFF!", 23, "Hardcore punk", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Ohio Players", 23, "Funk", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["OK Go", 23, "Alt-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Old Crow Medicine Show", 23, "Americana", "harmony-focused vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["Old Dominion", 23, "Country-pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Olivia Newton-John", 23, "Pop", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["OMD (Orchestral Manoeuvres in the Dark)", 23, "Synth-pop", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["One Direction", 23, "Pop", "harmony-focused vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["OneRepublic", 23, "Pop-rock", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Opeth", 23, "Progressive metal", "textured raspy vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Orange Juice", 23, "Indie-pop", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Ornette Coleman", 23, "Jazz", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Orville Peck", 23, "Alt-country", "male lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Otis Redding", 23, "Soul", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Our Lady Peace", 23, "Alt-rock", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Outlawz", 23, "Hip-hop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Overkill", 23, "Thrash metal", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Owl City", 23, "Synth-pop", "smooth intimate vocals", "synth-driven production", "distinctive song character"],
  ["Ozzy Osbourne", 23, "Heavy metal", "male lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["P!nk", 24, "Pop-rock", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Panic! At The Disco", 24, "Emo-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Paramore", 24, "Pop-punk", "female lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Patsy Cline", 24, "Country", "female lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Pat Benatar", 24, "Rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Pat Green", 24, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Paul Anka", 24, "Pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Paul Simon", 24, "Folk-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Paula Abdul", 24, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Paula Cole", 24, "Pop-rock", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Pavement", 24, "Indie rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Pavlo", 24, "Instrumental", "instrumental / production-led", "guitar-led arrangement", "distinctive song character"],
  ["Peabo Bryson", 24, "R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Pentatonix", 24, "A cappella", "harmony-focused vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Pere Ubu", 24, "Avant-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Pet Shop Boys", 24, "Synth-pop", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["Peter Gabriel", 24, "Prog-pop", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Peter Frampton", 24, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Pharrell Williams", 24, "Pop-R&B", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Phish", 24, "Jam band", "expressive lead vocals", "bass and groove focus", "distinctive song character"],
  ["Phoebe Bridgers", 24, "Indie-folk", "female lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Phil Collins", 24, "Pop-rock", "male lead vocals", "rhythm-forward percussion", "emotion-led storytelling"],
  ["Philip Glass", 25, "Minimalist classical", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Phishbone (Fishbone)", 25, "Funk-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Phoebe Snow", 25, "Jazz-pop", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Phyllis Hyman", 25, "Soul", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Piano Guys", 25, "Classical-pop", "instrumental / production-led", "piano / keyboard-led arrangement", "dreamy spacious atmosphere"],
  ["Piano Magic", 25, "Ambient pop", "expressive lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Pink", 25, "R&B (early)", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Pixies", 25, "Alt-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["PJ Harvey", 25, "Alt-rock", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Placebo", 25, "Alt-rock", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Plain White T’s", 25, "Pop-rock", "male lead vocals", "organic acoustic instrumentation", "emotion-led storytelling"],
  ["Plan B", 25, "Hip-hop-soul", "textured raspy vocals", "rhythm-forward percussion", "dreamy spacious atmosphere"],
  ["Poco", 25, "Country-rock", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["Poison", 25, "Glam metal", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Poliça", 25, "Synth-pop", "female lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["Portugal. The Man", 25, "Indie rock", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Primal Scream", 25, "Rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Primus", 25, "Funk-metal", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Prodigy", 25, "Electronic", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Public Enemy", 25, "Hip-hop", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Pulp", 25, "Britpop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Pussycat Dolls", 25, "Pop", "rhythmic rap delivery", "signature layered arrangement", "distinctive song character"],
  ["Q-Tip", 26, "Hip-hop", "smooth intimate vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Quantic", 26, "Electronic", "expressive lead vocals", "bass and groove focus", "distinctive song character"],
  ["Quarterflash", 26, "Rock", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Quasi", 26, "Indie rock", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Quavo", 26, "Hip-hop", "rhythmic rap delivery", "rhythm-forward percussion", "distinctive song character"],
  ["Quazar", 26, "Funk", "expressive lead vocals", "synth-driven production", "distinctive song character"],
  ["Quella Vecchia Locanda", 26, "Prog-rock", "male lead vocals", "orchestral / string layers", "distinctive song character"],
  ["Queens of the Stone Age", 26, "Rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Queensrÿche", 26, "Prog-metal", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Quiet Riot", 26, "Glam metal", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Quicksilver Messenger Service", 26, "Psychedelic rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Quincy", 26, "Soul-jazz", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Quincy Punx", 26, "Punk", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Quincy Coleman", 26, "Singer-songwriter", "female lead vocals", "organic acoustic instrumentation", "dreamy spacious atmosphere"],
  ["Quintessence", 26, "Jazz fusion", "instrumental / production-led", "signature layered arrangement", "distinctive song character"],
  ["Quintino", 26, "EDM", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Quirino Mendoza y Cortés", 26, "Traditional", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Quit Your Dayjob", 26, "Punk-electro", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Quivers", 26, "Indie-pop", "expressive lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Quix", 26, "EDM", "instrumental / production-led", "rhythm-forward percussion", "distinctive song character"],
  ["Quo Vadis", 26, "Death metal", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Quorthon (Bathory)", 26, "Black metal", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["R.E.O. Speedwagon", 27, "Rock", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Rachael Yamagata", 27, "Indie-pop", "female lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Rachel Platten", 27, "Pop", "female lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Rage Against the Machine", 27, "Rap-rock", "rhythmic rap delivery", "guitar-led arrangement", "distinctive song character"],
  ["Rag’n’Bone Man", 27, "Soul-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Rainbow", 27, "Hard rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Rainn", 27, "Christian pop", "female lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Rammstein", 27, "Industrial metal", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Randy Newman", 27, "Singer-songwriter", "male lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Randy Travis", 27, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Rascal Flatts", 27, "Country-pop", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Rat Pack (Sinatra, Martin, Davis Jr.)", 27, "Jazz-pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Ratatat", 27, "Electronic rock", "instrumental / production-led", "guitar-led arrangement", "distinctive song character"],
  ["Ray LaMontagne", 27, "Folk-rock", "textured raspy vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Ray Price", 27, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Ray Stevens", 27, "Comedy-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Razorlight", 27, "Indie rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Reba McEntire", 27, "Country", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Rebecca Black", 27, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Rebirth Brass Band", 27, "Jazz-funk", "expressive lead vocals", "bass and groove focus", "distinctive song character"],
  ["Redbone", 27, "Funk-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Reel Big Fish", 27, "Ska-punk", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Refused", 28, "Hardcore punk", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Regina Spektor", 28, "Indie-pop", "female lead vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["REO Cragun", 28, "Hip-hop", "male lead vocals", "rhythm-forward percussion", "dreamy spacious atmosphere"],
  ["Richard Marx", 28, "Soft rock", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Rick Astley", 28, "Pop", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Rick James", 28, "Funk", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Rick Ross", 28, "Hip-hop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Ricky Martin", 28, "Latin pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Rico Nasty", 28, "Hip-hop", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Ride", 28, "Shoegaze", "male lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Righteous Brothers", 28, "Soul-pop", "male lead vocals", "orchestral / string layers", "emotion-led storytelling"],
  ["Rilo Kiley", 28, "Indie rock", "female lead vocals", "signature layered arrangement", "era-conscious retro character"],
  ["Rita Coolidge", 28, "Pop-country", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Rita Ora", 28, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Ritchie Valens", 28, "Rock & roll", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Rob Thomas", 28, "2000s Pop-rock", "textured raspy vocals", "signature layered arrangement", "era-conscious retro character"],
  ["Rob Zombie", 28, "Metal", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Roberta Flack", 28, "Soul", "smooth intimate vocals", "piano / keyboard-led arrangement", "distinctive song character"],
  ["Robin Thicke", 28, "R&B", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Robyn", 28, "Pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Rod Stewart", 28, "Rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Roger Miller", 28, "Country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Sade", 29, "Smooth soul", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Sam Hunt", 29, "Country-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Sam Smith", 29, "Pop-soul", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Santana", 29, "Latin rock", "instrumental / production-led", "guitar-led arrangement", "distinctive song character"],
  ["Sarah McLachlan", 29, "Pop", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Savage Garden", 29, "Pop", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Scissor Sisters", 29, "Dance-pop", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Scorpions", 29, "Hard rock", "powerful high-impact vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Scotty McCreery", 29, "Country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Seal", 29, "Pop-soul", "powerful high-impact vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Sebastian Yatra", 29, "Latin pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Seether", 29, "Post-grunge", "textured raspy vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Selena", 29, "Tejano pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Selena Gomez", 29, "Pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Semisonic", 29, "Alt-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Sensational Alex Harvey Band", 29, "Rock", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Sepultura", 29, "Metal", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Serj Tankian", 29, "Alt-metal", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Sergio Mendes", 29, "Latin jazz", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Sex Pistols", 29, "Punk rock", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Shania Twain", 29, "Country-pop", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Shinedown", 29, "Alt-metal", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Shirley Bassey", 30, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Shirley Caesar", 30, "Gospel", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Shooter Jennings", 30, "Country-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Showaddywaddy", 30, "Rock & roll revival", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Sigur Rós", 30, "Post-rock", "expressive lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Silversun Pickups", 30, "Alt-rock", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Simple Minds", 30, "New wave", "powerful high-impact vocals", "synth-driven production", "distinctive song character"],
  ["Simple Plan", 30, "Pop-punk", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Sinead O’Connor", 30, "Pop", "female lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Siouxsie and the Banshees", 30, "Post-punk", "female lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Sister Rosetta Tharpe", 30, "Gospel-rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Sisters of Mercy", 30, "Goth rock", "male lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["Sixpence None the Richer", 30, "Pop", "smooth intimate vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Skepta", 30, "UK grime", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Skid Row", 30, "Glam metal", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Skrillex", 30, "EDM", "expressive lead vocals", "synth-driven production", "distinctive song character"],
  ["Sky Ferreira", 30, "Indie-pop", "female lead vocals", "signature layered arrangement", "era-conscious retro character"],
  ["Sleater-Kinney", 30, "Punk-rock", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Sly & the Family Stone", 30, "Funk-soul", "female lead vocals", "bass and groove focus", "distinctive song character"],
  ["Smash Mouth", 30, "Pop-rock", "textured raspy vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Smashing Pumpkins", 30, "Alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Smokey Robinson", 30, "Motown soul", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Snow Patrol", 31, "Indie rock", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Snow", 31, "Reggae-pop", "rhythmic rap delivery", "rhythm-forward percussion", "distinctive song character"],
  ["Social Distortion", 31, "Punk rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Sodom", 31, "Thrash metal", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Soft Cell", 31, "Synth-pop", "male lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["Solange", 31, "R&B", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Son House", 31, "Delta blues", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Sonic Youth", 31, "Noise rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Sonny Rollins", 31, "Jazz", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Sonny & Cher", 31, "Pop duo", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Soundgarden", 31, "Grunge", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Spandau Ballet", 31, "New wave", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Sparks", 31, "Art-pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Spice Girls", 31, "Pop", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Spin Doctors", 31, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Spirit", 31, "Psychedelic rock", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Spiritualized", 31, "Space rock", "expressive lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Spoon", 31, "Indie rock", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Spooky Tooth", 31, "Rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["Staind", 31, "Post-grunge", "male lead vocals", "guitar-led arrangement", "dark atmospheric mood"],
  ["Status Quo", 31, "Rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Steely Dan", 31, "Jazz-rock", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["T-Pain", 32, "Hip-hop/R&B", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Tame Impala", 32, "Psychedelic pop-rock", "expressive lead vocals", "synth-driven production", "dreamy spacious atmosphere"],
  ["Taylor Swift", 32, "Pop-country crossover", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Tears for Fears", 32, "80s new wave", "male lead vocals", "synth-driven production", "uplifting high-energy arc"],
  ["Ted Nugent", 32, "Hard rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Tegan and Sara", 32, "Indie-pop", "harmony-focused vocals", "synth-driven production", "emotion-led storytelling"],
  ["Television", 32, "Proto-punk", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Temple of the Dog", 32, "Grunge supergroup", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Tenacious D", 32, "Comedy rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Band Perry", 32, "Country-pop", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["The Chainsmokers", 32, "EDM-pop", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["The Doobie Brothers", 32, "Classic rock", "harmony-focused vocals", "bass and groove focus", "distinctive song character"],
  ["The Drifters", 32, "Doo-wop & R&B", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["The Everly Brothers", 32, "50s country-pop", "harmony-focused vocals", "organic acoustic instrumentation", "distinctive song character"],
  ["The Fray", 32, "2000s alt-rock", "male lead vocals", "piano / keyboard-led arrangement", "emotion-led storytelling"],
  ["The Guess Who", 32, "Classic rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Hollies", 32, "British Invasion pop", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Human League", 32, "80s synth-pop", "female lead vocals", "synth-driven production", "distinctive song character"],
  ["The Jam", 32, "Punk rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Jonas Brothers", 32, "Pop-rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["The Lumineers", 32, "Indie-folk", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["The Mamas & the Papas", 32, "60s folk-pop", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Thin Lizzy", 33, "Hard rock", "textured raspy vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Third Eye Blind", 33, "90s alt-rock", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Thirty Seconds to Mars", 33, "Arena rock", "powerful high-impact vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Three 6 Mafia", 33, "Southern hip-hop", "rhythmic rap delivery", "rhythm-forward percussion", "dark atmospheric mood"],
  ["Three Days Grace", 33, "Post-grunge", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Tim McGraw", 33, "Modern country", "male lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Tinashe", 33, "R&B-pop", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Tina Turner", 33, "Rock & soul powerhouse", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Toad the Wet Sprocket", 33, "90s alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Tom Jones", 33, "Crooner", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Tom Petty", 33, "Heartland rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Tommy James & the Shondells", 33, "60s pop-rock", "harmony-focused vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Toni Braxton", 33, "R&B ballads", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Tony Bennett", 33, "Classic jazz pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Tori Amos", 33, "Piano-driven alt-pop", "female lead vocals", "piano / keyboard-led arrangement", "emotion-led storytelling"],
  ["Toto", 33, "Soft rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Trapt", 33, "2000s alt-metal", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Trisha Yearwood", 33, "Country", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Troye Sivan", 33, "Electropop", "smooth intimate vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Truth Hurts", 33, "R&B", "female lead vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Tupac", 33, "West Coast hip-hop", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Ty Dolla $ign", 33, "Hip-hop/R&B", "smooth intimate vocals", "rhythm-forward percussion", "distinctive song character"],
  ["The Band", 34, "Roots rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["The Beach Boys", 34, "60s surf rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["The Beatles", 34, "60s Brit pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["The Black Crowes", 34, "Blues rock", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Black Keys", 34, "Garage rock", "expressive lead vocals", "guitar-led arrangement", "era-conscious retro character"],
  ["The Byrds", 34, "60s folk rock", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Cars", 34, "New wave rock", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["The Clash", 34, "Punk rock", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["The Commodores", 34, "Funk & soul", "harmony-focused vocals", "bass and groove focus", "distinctive song character"],
  ["The Cranberries", 34, "90s alt-rock", "female lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["The Cure", 34, "Goth rock", "male lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["The Doors", 34, "Psychedelic rock", "male lead vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["The Eagles", 34, "Classic rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["The Flaming Lips", 34, "Psychedelic alt-rock", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["The Isley Brothers", 34, "R&B", "harmony-focused vocals", "bass and groove focus", "distinctive song character"],
  ["The Jackson 5", 34, "Motown pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["The Killers", 34, "Indie rock", "expressive lead vocals", "synth-driven production", "uplifting high-energy arc"],
  ["The Kinks", 34, "British Invasion rock", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Offspring", 34, "90s punk rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["The Police", 34, "New wave rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["The Rolling Stones", 34, "Rock & roll legends", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["The Velvet Underground", 34, "Avant-garde rock", "textured raspy vocals", "signature layered arrangement", "distinctive song character"],
  ["U2", 35, "Arena rock", "powerful high-impact vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["UB40", 35, "Reggae-pop", "smooth intimate vocals", "bass and groove focus", "distinctive song character"],
  ["Ultravox", 35, "80s new wave", "male lead vocals", "synth-driven production", "dark atmospheric mood"],
  ["Umphrey’s McGee", 35, "Jam band", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Uncle Kracker", 35, "Country-pop crossover", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Underoath", 35, "Metalcore", "textured raspy vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Unwritten Law", 35, "Punk rock", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Usher", 35, "R&B-pop", "smooth intimate vocals", "bass and groove focus", "emotion-led storytelling"],
  ["Uriah Heep", 35, "70s hard rock", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Utada Hikaru", 35, "J-pop", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["The Unthanks", 35, "Folk", "harmony-focused vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Union J", 35, "British boy band", "harmony-focused vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Unknown Mortal Orchestra", 35, "Psychedelic indie rock", "male lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["Ulrich Schnauss", 35, "Ambient electronica", "expressive lead vocals", "synth-driven production", "dreamy spacious atmosphere"],
  ["Ugly Kid Joe", 35, "90s hard rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Unkle", 35, "Trip-hop", "expressive lead vocals", "rhythm-forward percussion", "dark atmospheric mood"],
  ["Utopia", 35, "progressive pop-rock", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["UFO", 35, "70s hard rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Uncle Tupelo", 35, "Alt-country pioneers", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Unspoken", 35, "Contemporary Christian", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Underworld", 35, "Electronic", "male lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Us3", 35, "Acid jazz", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Van Halen", 36, "Hard rock", "male lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Van Morrison", 36, "Singer-songwriter", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Vanessa Carlton", 36, "Pop-rock", "female lead vocals", "piano / keyboard-led arrangement", "era-conscious retro character"],
  ["Vanessa Williams", 36, "R&B-pop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Velvet Revolver", 36, "Hard rock supergroup", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Vengaboys", 36, "Eurodance", "expressive lead vocals", "synth-driven production", "distinctive song character"],
  ["Vera Lynn", 36, "Traditional pop", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Veruca Salt", 36, "90s alt-rock", "harmony-focused vocals", "guitar-led arrangement", "distinctive song character"],
  ["Vertical Horizon", 36, "2000s alt-rock", "male lead vocals", "signature layered arrangement", "era-conscious retro character"],
  ["The Verve", 36, "Britpop", "male lead vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["The Verve Pipe", 36, "90s alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Vicki Sue Robinson", 36, "Disco", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Victor Wooten", 36, "Jazz fusion", "expressive lead vocals", "bass and groove focus", "distinctive song character"],
  ["Vince Gill", 36, "Country", "smooth intimate vocals", "guitar-led arrangement", "emotion-led storytelling"],
  ["Violent Femmes", 36, "Folk-punk", "male lead vocals", "organic acoustic instrumentation", "emotion-led storytelling"],
  ["Viper", 36, "Brazilian metal", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Virginia to Vegas", 36, "Electropop", "smooth intimate vocals", "signature layered arrangement", "distinctive song character"],
  ["Vitamin C", 36, "2000s pop", "female lead vocals", "rhythm-forward percussion", "era-conscious retro character"],
  ["Vivian Green", 36, "R&B", "smooth intimate vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Voivod", 36, "Canadian thrash metal", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Volbeat", 36, "Danish rock", "male lead vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Walk the Moon", 37, "Indie pop", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["Wale", 37, "Hip-hop", "smooth intimate vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Wallflowers", 37, "90s alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Wanda Jackson", 37, "Rockabilly pioneer", "female lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Wang Chung", 37, "80s new wave", "expressive lead vocals", "synth-driven production", "distinctive song character"],
  ["War", 37, "Funk-rock", "male lead vocals", "bass and groove focus", "distinctive song character"],
  ["Warren Zevon", 37, "Singer-songwriter", "male lead vocals", "piano / keyboard-led arrangement", "dark atmospheric mood"],
  ["Washed Out", 37, "Chillwave", "male lead vocals", "synth-driven production", "dreamy spacious atmosphere"],
  ["Waylon Jennings", 37, "Outlaw country", "textured raspy vocals", "guitar-led arrangement", "distinctive song character"],
  ["Weezer", 37, "Alt-rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Westlife", 37, "Boy band pop", "harmony-focused vocals", "signature layered arrangement", "emotion-led storytelling"],
  ["Wham!", 37, "80s pop duo", "male lead vocals", "synth-driven production", "distinctive song character"],
  ["Whiskeytown", 37, "Alt-country", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Whitesnake", 37, "Hard rock", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["Whitney Houston", 37, "Pop-R&B", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Wilco", 37, "Alt-country", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Willie Nelson", 37, "Country legend", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Wilson Phillips", 37, "90s pop", "harmony-focused vocals", "signature layered arrangement", "uplifting high-energy arc"],
  ["Wolf Alice", 37, "Indie rock", "female lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Wolfmother", 37, "Hard rock", "powerful high-impact vocals", "guitar-led arrangement", "era-conscious retro character"],
  ["Wu-Tang Clan", 37, "Hip-hop collective", "textured raspy vocals", "rhythm-forward percussion", "distinctive song character"],
  ["X Ambassadors", 38, "Indie pop-rock", "male lead vocals", "signature layered arrangement", "dreamy spacious atmosphere"],
  ["X Japan", 38, "Japanese metal", "powerful high-impact vocals", "guitar-led arrangement", "distinctive song character"],
  ["XTC", 38, "New wave", "expressive lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Xscape", 38, "90s R&B", "harmony-focused vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Yeah Yeah Yeahs", 38, "Indie rock", "female lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Yello", 38, "Electronic pop", "expressive lead vocals", "synth-driven production", "distinctive song character"],
  ["Yellowcard", 38, "Pop-punk", "expressive lead vocals", "guitar-led arrangement", "uplifting high-energy arc"],
  ["Yes", 38, "Progressive rock", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["YG", 38, "West Coast hip-hop", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Yo La Tengo", 38, "Indie rock", "male lead vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Yoko Ono", 38, "Avant-garde artist", "expressive lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Youssou N’Dour", 38, "Senegalese pop", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["Young Jeezy", 38, "Southern rap", "textured raspy vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Young Thug", 38, "Hip-hop", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Young the Giant", 38, "Indie rock", "powerful high-impact vocals", "guitar-led arrangement", "dreamy spacious atmosphere"],
  ["Yusuf / Cat Stevens", 38, "Folk-rock", "male lead vocals", "signature layered arrangement", "distinctive song character"],
  ["ZZ Top", 38, "Southern rock", "male lead vocals", "guitar-led arrangement", "distinctive song character"],
  ["Zac Brown Band", 38, "Country", "harmony-focused vocals", "signature layered arrangement", "distinctive song character"],
  ["Zara Larsson", 38, "Pop", "powerful high-impact vocals", "signature layered arrangement", "distinctive song character"],
  ["Zayn", 38, "Pop-R&B", "smooth intimate vocals", "signature layered arrangement", "dark atmospheric mood"],
  ["Zero 7", 38, "Downtempo electronica", "female lead vocals", "rhythm-forward percussion", "distinctive song character"],
  ["Ziggy Marley", 38, "Reggae", "expressive lead vocals", "rhythm-forward percussion", "distinctive song character"],
] as const;
