import type { SunoTechnique } from "./suno-practice-library.ts";

const STUDIO_SOURCES = [
  "Suno V4.5 Detailed Style Instructions",
  "Suno Studio Export",
  "Spotify Loudness Normalization",
  "AIPOGER Suno Songwriting Skill",
];

export const SUNO_STUDIO_MASTERING_MOVES: SunoTechnique<"mastering">[] = [
  {
    key: "studio-mastering-general",
    category: "mastering",
    title: { zh: "一般通用錄音室 Mastering", en: "General studio mastering" },
    summary: { zh: "不指定曲風時的通用 Style 底稿：先把人聲、低頻、瞬態、聲場與動態講清楚。這是生成方向，不是真正的後製命令。", en: "A genre-neutral Style baseline for vocal clarity, low-end control, transients, stereo image, and dynamics. It is a generation direction, not a literal post-mastering command." },
    use: { zh: "任何曲風都想先建立乾淨、可發表的錄音室質感時", en: "When any genre needs a clean, release-ready studio direction" },
    copy: { zh: "High-fidelity studio production, polished final stereo mix, clear forward lead vocal, controlled low end, tight kick and bass separation, smooth high frequencies, punchy but preserved transients, coherent stereo image, natural depth, balanced dynamics, no clipping, no harsh distortion", en: "High-fidelity studio production, polished final stereo mix, clear forward lead vocal, controlled low end, tight kick and bass separation, smooth high frequencies, punchy but preserved transients, coherent stereo image, natural depth, balanced dynamics, no clipping, no harsh distortion" },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["studio", "mastering", "mix", "master", "high fidelity", "clean", "錄音室", "母帶", "通用"],
  },
  {
    key: "studio-mastering-acoustic-folk",
    category: "mastering",
    title: { zh: "Acoustic Folk 錄音室母帶", en: "Acoustic folk studio master" },
    summary: { zh: "保留木吉他與人聲的自然細節，不用過度壓縮換取音量。", en: "Preserves acoustic detail and vocal intimacy instead of trading dynamics for loudness." },
    use: { zh: "民謠、創作歌手、木吉他作品", en: "Folk, singer-songwriter, and acoustic guitar tracks" },
    copy: { zh: "Warm acoustic singer-songwriter folk, 88 BPM, G major, intimate conversational lead vocal, fingerpicked guitar carries the pulse, upright bass and brushed drums enter gently, cello answers the final chorus, lyrics about finding the way home, close-room natural reverb, transparent stereo master, gentle tape glue, preserved dynamics, no brittle highs.", en: "Warm acoustic singer-songwriter folk, 88 BPM, G major, intimate conversational lead vocal, fingerpicked guitar carries the pulse, upright bass and brushed drums enter gently, cello answers the final chorus, lyrics about finding the way home, close-room natural reverb, transparent stereo master, gentle tape glue, preserved dynamics, no brittle highs." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["acoustic", "folk", "singer-songwriter", "natural", "木吉他", "民謠"],
  },
  {
    key: "studio-mastering-piano-pop",
    category: "mastering",
    title: { zh: "Piano Pop Ballad 錄音室母帶", en: "Piano pop ballad studio master" },
    summary: { zh: "讓鋼琴與主唱站在中心，副歌放大但不要把情緒壓扁。", en: "Keeps piano and lead vocal centered while the chorus expands without flattening emotion." },
    use: { zh: "鋼琴抒情、流行慢歌、告白歌", en: "Piano ballads, pop slow songs, and intimate confessionals" },
    copy: { zh: "Piano-led pop ballad, 72 BPM, C major, expressive alto lead, felt piano and soft strings, restrained verse into an open soaring chorus, lyrics about saying goodbye with gratitude, vocal-forward studio mix, clean low-mid control, smooth de-essed top end, natural stereo width, polished final master with breathing room.", en: "Piano-led pop ballad, 72 BPM, C major, expressive alto lead, felt piano and soft strings, restrained verse into an open soaring chorus, lyrics about saying goodbye with gratitude, vocal-forward studio mix, clean low-mid control, smooth de-essed top end, natural stereo width, polished final master with breathing room." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["piano", "pop", "ballad", "vocal forward", "鋼琴", "抒情"],
  },
  {
    key: "studio-mastering-dream-pop",
    category: "mastering",
    title: { zh: "Dream Pop／Indie Pop 錄音室母帶", en: "Dream pop / indie pop studio master" },
    summary: { zh: "保留夢幻寬度，同時控制低頻與人聲遮蔽，讓旋律仍然清楚。", en: "Keeps the haze wide while controlling sub energy and vocal masking so the melody stays clear." },
    use: { zh: "夢幻流行、獨立流行、夜行氛圍歌", en: "Dream pop, indie pop, and nocturnal atmosphere tracks" },
    copy: { zh: "Dream pop with indie-pop hooks, 104 BPM, B major, airy breathy lead and layered harmonies, chorus guitars, analog synth haze, round bass, and soft live drums, intimate verses expanding into a luminous chorus, lyrics about a night drive, glossy warm stereo master, controlled sub, smooth transients, no vocal masking.", en: "Dream pop with indie-pop hooks, 104 BPM, B major, airy breathy lead and layered harmonies, chorus guitars, analog synth haze, round bass, and soft live drums, intimate verses expanding into a luminous chorus, lyrics about a night drive, glossy warm stereo master, controlled sub, smooth transients, no vocal masking." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["dream pop", "indie pop", "wide", "haze", "夢幻", "獨立流行"],
  },
  {
    key: "studio-mastering-alt-rock",
    category: "mastering",
    title: { zh: "Alternative Rock 錄音室母帶", en: "Alternative rock studio master" },
    summary: { zh: "讓吉他、鼓與主唱各自有位置，保留現場感與副歌衝擊。", en: "Gives guitars, drums, and vocal their own space while keeping live energy and chorus impact." },
    use: { zh: "另類搖滾、樂團作品、現場感編曲", en: "Alternative rock, band recordings, and live-feeling arrangements" },
    copy: { zh: "Alternative rock, 128 BPM, E minor, urgent raspy lead, overdriven guitars answer the vocal, live kick and snare drive the song, bass locks to the riff, quiet verse into a massive human chorus, lyrics about breaking a cycle, punchy studio mix, guitar clarity, tight low end, coherent stereo image, loud without crushing the drums.", en: "Alternative rock, 128 BPM, E minor, urgent raspy lead, overdriven guitars answer the vocal, live kick and snare drive the song, bass locks to the riff, quiet verse into a massive human chorus, lyrics about breaking a cycle, punchy studio mix, guitar clarity, tight low end, coherent stereo image, loud without crushing the drums." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["alternative rock", "rock", "guitar", "live drums", "另類搖滾", "樂團"],
  },
  {
    key: "studio-mastering-pop-punk",
    category: "mastering",
    title: { zh: "Pop Punk 錄音室母帶", en: "Pop punk studio master" },
    summary: { zh: "維持快速、明亮、群唱有衝擊的聲音，但避免高頻刺耳。", en: "Keeps the fast, bright, gang-vocal energy while avoiding an abrasive upper midrange." },
    use: { zh: "青春搖滾、運動片段、熱血短片", en: "Youth rock, sports edits, and energetic short-form video" },
    copy: { zh: "Modern pop-punk, 174 BPM, D major, bright youthful lead with gang-vocal responses, fast palm-muted guitars, melodic octave lead, punchy live drums, and melodic bass, explosive pre-chorus into a chantable chorus, lyrics about starting over, crisp radio-ready mix, tight kick-bass pocket, energetic transients, controlled upper mids, polished master without harsh clipping.", en: "Modern pop-punk, 174 BPM, D major, bright youthful lead with gang-vocal responses, fast palm-muted guitars, melodic octave lead, punchy live drums, and melodic bass, explosive pre-chorus into a chantable chorus, lyrics about starting over, crisp radio-ready mix, tight kick-bass pocket, energetic transients, controlled upper mids, polished master without harsh clipping." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["pop punk", "punk", "gang vocals", "radio-ready", "青春", "群唱"],
  },
  {
    key: "studio-mastering-neo-soul",
    category: "mastering",
    title: { zh: "Neo-Soul／R&B 錄音室母帶", en: "Neo-soul / R&B studio master" },
    summary: { zh: "以 Groove、低頻與主唱細節為中心，保留溫暖和聲與自然動態。", en: "Centers the groove, low end, and vocal detail while preserving warm harmony and natural dynamics." },
    use: { zh: "Neo-Soul、R&B、情緒律動作品", en: "Neo-soul, R&B, and groove-led emotional tracks" },
    copy: { zh: "Neo-soul R&B, 82 BPM, F-sharp minor, warm smoky lead with tasteful melisma, Rhodes chords, muted guitar, round electric bass, pocketed drums, and subtle harmony stacks, verses sit behind the groove before a velvet chorus, lyrics about guarded intimacy, rich analog-style mix, smooth sub control, deep stable stereo field, natural dynamics.", en: "Neo-soul R&B, 82 BPM, F-sharp minor, warm smoky lead with tasteful melisma, Rhodes chords, muted guitar, round electric bass, pocketed drums, and subtle harmony stacks, verses sit behind the groove before a velvet chorus, lyrics about guarded intimacy, rich analog-style mix, smooth sub control, deep stable stereo field, natural dynamics." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["neo soul", "r&b", "rhodes", "groove", "靈魂樂", "律動"],
  },
  {
    key: "studio-mastering-hip-hop-trap",
    category: "mastering",
    title: { zh: "Hip-Hop／Trap 錄音室母帶", en: "Hip-hop / trap studio master" },
    summary: { zh: "保留 Rap 咬字與 808 的重量，讓低頻集中、踢鼓清楚、不糊成一團。", en: "Preserves rap diction and 808 weight with a focused low end and a kick that stays audible." },
    use: { zh: "Rap、Trap、暗黑嘻哈、短影音 Hook", en: "Rap, trap, dark hip-hop, and short-form hooks" },
    copy: { zh: "Melodic hip-hop trap, 142 BPM, F minor, confident close-mic rap lead with a sung hook, sparse piano motif, deep 808 anchors, crisp hi-hats, snare snaps, and dark pads, verses leave space for cadence before a heavy hook, lyrics about ambition under pressure, clean vocal pocket, mono-compatible sub, punchy master without smeared bass.", en: "Melodic hip-hop trap, 142 BPM, F minor, confident close-mic rap lead with a sung hook, sparse piano motif, deep 808 anchors, crisp hi-hats, snare snaps, and dark pads, verses leave space for cadence before a heavy hook, lyrics about ambition under pressure, clean vocal pocket, mono-compatible sub, punchy master without smeared bass." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["hip-hop", "trap", "rap", "808", "mono sub", "嘻哈", "低頻"],
  },
  {
    key: "studio-mastering-vocal-jazz",
    category: "mastering",
    title: { zh: "Vocal Jazz 錄音室母帶", en: "Vocal jazz studio master" },
    summary: { zh: "以自然房間、真實瞬態與主唱咬字為主，不使用過度寬化或過度限制。", en: "Prioritizes natural room, real transients, and vocal diction without excessive widening or limiting." },
    use: { zh: "爵士人聲、酒吧現場、成熟敘事歌曲", en: "Vocal jazz, lounge-room recordings, and mature narrative songs" },
    copy: { zh: "Modern vocal jazz, 96 BPM, B-flat major, intimate jazz vocal with precise diction, upright bass walks beneath brushed drums, warm piano voicings, muted trumpet replies, and restrained guitar comp, dynamic verse-to-chorus lift with a short improvisational outro, lyrics about a late-night conversation, natural room tone, transparent mastering, preserved transients, centered low end.", en: "Modern vocal jazz, 96 BPM, B-flat major, intimate jazz vocal with precise diction, upright bass walks beneath brushed drums, warm piano voicings, muted trumpet replies, and restrained guitar comp, dynamic verse-to-chorus lift with a short improvisational outro, lyrics about a late-night conversation, natural room tone, transparent mastering, preserved transients, centered low end." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["jazz", "vocal jazz", "upright bass", "natural room", "爵士", "自然空間"],
  },
  {
    key: "studio-mastering-nu-disco",
    category: "mastering",
    title: { zh: "Nu-Disco／Funk 錄音室母帶", en: "Nu-disco / funk studio master" },
    summary: { zh: "讓 Bass、Clavinet、四拍 Kick 與群唱一起有舞池推力，但不犧牲高頻的順滑度。", en: "Gives bass, clavinet, four-on-the-floor kick, and gang vocals dancefloor push without sacrificing smooth highs." },
    use: { zh: "Disco、Funk、派對與舞池作品", en: "Disco, funk, party, and dancefloor tracks" },
    copy: { zh: "Nu-disco funk, 118 BPM, A minor, charismatic lead with call-and-response backing vocals, syncopated electric bass, clavinet, clean rhythm guitar, four-on-the-floor kick, handclaps, and bright strings, pre-chorus lift into a dancefloor chorus, lyrics about a second chance, punchy polished mix, tight kick-bass separation, crisp smooth highs, wide chorus, no pumping.", en: "Nu-disco funk, 118 BPM, A minor, charismatic lead with call-and-response backing vocals, syncopated electric bass, clavinet, clean rhythm guitar, four-on-the-floor kick, handclaps, and bright strings, pre-chorus lift into a dancefloor chorus, lyrics about a second chance, punchy polished mix, tight kick-bass separation, crisp smooth highs, wide chorus, no pumping." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["nu disco", "funk", "disco", "clavinet", "舞池", "放克"],
  },
  {
    key: "studio-mastering-deep-house",
    category: "mastering",
    title: { zh: "Deep House 錄音室母帶", en: "Deep house studio master" },
    summary: { zh: "控制 Club 低頻與側鏈呼吸，讓人聲、Rhodes 與 Drop 保持乾淨。", en: "Controls club sub and sidechain breathing so vocal, Rhodes, and drop remain clean." },
    use: { zh: "Deep House、夜店、時尚與 Lounge 舞曲", en: "Deep house, nightlife, fashion, and lounge dance tracks" },
    copy: { zh: "Deep house, 122 BPM, F-sharp minor, soulful restrained vocal, four-on-the-floor kick, warm sub bass, shuffled hats, Rhodes, filtered chords, and subtle percussive fills, gradual tension into a clean melodic drop, lyrics about losing track of time on the dancefloor, club-ready studio master, controlled sub, sidechain breathing, phase-coherent width, smooth top end.", en: "Deep house, 122 BPM, F-sharp minor, soulful restrained vocal, four-on-the-floor kick, warm sub bass, shuffled hats, Rhodes, filtered chords, and subtle percussive fills, gradual tension into a clean melodic drop, lyrics about losing track of time on the dancefloor, club-ready studio master, controlled sub, sidechain breathing, phase-coherent width, smooth top end." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["deep house", "house", "club", "sidechain", "夜店", "舞曲"],
  },
  {
    key: "studio-mastering-melodic-techno",
    category: "mastering",
    title: { zh: "Melodic Techno 錄音室母帶", en: "Melodic techno studio master" },
    summary: { zh: "保持低頻單聲道穩定、上層空間寬闊，讓機械節奏的瞬態不被限制器磨平。", en: "Keeps the low end mono-stable and the upper atmosphere wide while preserving mechanical transients." },
    use: { zh: "Melodic Techno、地下舞池、未來感影像", en: "Melodic techno, underground rooms, and futuristic visuals" },
    copy: { zh: "Driving melodic techno, 132 BPM, D minor, minimal vocal phrases used as texture, tight analog kick, rumbling mono sub, metallic percussion, hypnotic sequence, and dark evolving pads, slowly intensifying arrangement into a focused peak, lyrics about neon machinery, precise club mix, fast transient control, mono-stable low end, wide upper atmosphere, clean limiter behavior.", en: "Driving melodic techno, 132 BPM, D minor, minimal vocal phrases used as texture, tight analog kick, rumbling mono sub, metallic percussion, hypnotic sequence, and dark evolving pads, slowly intensifying arrangement into a focused peak, lyrics about neon machinery, precise club mix, fast transient control, mono-stable low end, wide upper atmosphere, clean limiter behavior." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["techno", "melodic techno", "club", "mono sub", "機械", "地下"],
  },
  {
    key: "studio-mastering-uplifting-trance",
    category: "mastering",
    title: { zh: "Uplifting Trance 錄音室母帶", en: "Uplifting trance studio master" },
    summary: { zh: "讓 Supersaw 與高頻保持明亮但不刺耳，保留主旋律細節與安全的立體聲寬度。", en: "Keeps supersaws bright without harshness, preserving melodic detail and a phase-safe stereo width." },
    use: { zh: "Trance、史詩舞曲、希望感副歌", en: "Trance, epic dance tracks, and hopeful choruses" },
    copy: { zh: "Uplifting trance, 138 BPM, A minor, clear emotional lead vocal with layered octave harmonies, rolling bass, gated plucks, shimmering arpeggios, snare build, and expansive supersaw chorus, intimate verse into a euphoric drop and final lift, lyrics about finding light after darkness, high-fidelity stereo master, clean sub, controlled brightness, phase-safe width, preserved melodic detail.", en: "Uplifting trance, 138 BPM, A minor, clear emotional lead vocal with layered octave harmonies, rolling bass, gated plucks, shimmering arpeggios, snare build, and expansive supersaw chorus, intimate verse into a euphoric drop and final lift, lyrics about finding light after darkness, high-fidelity stereo master, clean sub, controlled brightness, phase-safe width, preserved melodic detail." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["trance", "supersaw", "uplifting", "wide", "史詩", "希望"],
  },
  {
    key: "studio-mastering-liquid-dnb",
    category: "mastering",
    title: { zh: "Liquid Drum & Bass 錄音室母帶", en: "Liquid drum and bass studio master" },
    summary: { zh: "讓快速 Break、Reese Bass 與人聲同時清楚，保持流動感而不是整體扁平化。", en: "Keeps fast breaks, Reese bass, and vocal clear while preserving flow instead of flattening the track." },
    use: { zh: "Liquid D&B、情緒 Bass、快速但柔和的作品", en: "Liquid D&B, emotional bass, and fast but graceful tracks" },
    copy: { zh: "Liquid drum and bass, 174 BPM, C minor, soulful lead vocal, chopped breakbeats, warm Reese bass, piano fragments, atmospheric pads, and delicate guitar harmonics, verses float above the groove before a flowing melodic drop, lyrics about moving through rain, tight low-end management, crisp drum transients, smooth vocal presence, wide controlled ambience, energetic master without flattening the break.", en: "Liquid drum and bass, 174 BPM, C minor, soulful lead vocal, chopped breakbeats, warm Reese bass, piano fragments, atmospheric pads, and delicate guitar harmonics, verses float above the groove before a flowing melodic drop, lyrics about moving through rain, tight low-end management, crisp drum transients, smooth vocal presence, wide controlled ambience, energetic master without flattening the break." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["drum and bass", "liquid", "breakbeat", "reese bass", "快速", "流動"],
  },
  {
    key: "studio-mastering-synthwave",
    category: "mastering",
    title: { zh: "Cinematic Synthwave 錄音室母帶", en: "Cinematic synthwave studio master" },
    summary: { zh: "用 Tape 飽和、圓潤高頻與穩定 Mono Bass 做出復古但乾淨的夜行聲場。", en: "Uses tape saturation, rounded highs, and stable mono bass for a retro but clean night-drive field." },
    use: { zh: "Synthwave、復古電子、夜景與汽車影像", en: "Synthwave, retro electronic, night scenes, and driving visuals" },
    copy: { zh: "Cinematic synthwave, 100 BPM, E minor, low-register nostalgic lead, analog bass sequence, gated snare, vintage polysynth pads, arpeggiated synths, and restrained saxophone accent, night-drive verse into an expansive neon chorus, lyrics about memory and headlights, tape-warmed studio mix, rounded top end, firm mono bass, cohesive stereo width, gentle saturation, no harshness.", en: "Cinematic synthwave, 100 BPM, E minor, low-register nostalgic lead, analog bass sequence, gated snare, vintage polysynth pads, arpeggiated synths, and restrained saxophone accent, night-drive verse into an expansive neon chorus, lyrics about memory and headlights, tape-warmed studio mix, rounded top end, firm mono bass, cohesive stereo width, gentle saturation, no harshness." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["synthwave", "cinematic", "retro", "tape", "復古電子", "夜行"],
  },
  {
    key: "studio-mastering-orchestral-pop",
    category: "mastering",
    title: { zh: "Cinematic Orchestral Pop 錄音室母帶", en: "Cinematic orchestral pop studio master" },
    summary: { zh: "保留電影式動態與微細層次，讓主唱中心清楚，避免混成一片的長殘響。", en: "Preserves film-score dynamics and micro-detail while keeping the vocal center clear and the reverb controlled." },
    use: { zh: "電影感流行、預告片、史詩抒情歌", en: "Cinematic pop, trailers, and epic ballads" },
    copy: { zh: "Cinematic orchestral pop, 78 BPM, D minor, intimate baritone lead, piano and solo cello begin alone, strings and French horns widen the pre-chorus, timpani and full orchestra lift the final chorus, lyrics about choosing courage, wide film-score space with clear vocal center, transparent mastering, preserved microdynamics, controlled low-frequency impact, no excessive reverb wash.", en: "Cinematic orchestral pop, 78 BPM, D minor, intimate baritone lead, piano and solo cello begin alone, strings and French horns widen the pre-chorus, timpani and full orchestra lift the final chorus, lyrics about choosing courage, wide film-score space with clear vocal center, transparent mastering, preserved microdynamics, controlled low-frequency impact, no excessive reverb wash." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["cinematic", "orchestral", "strings", "film score", "電影感", "管弦"],
  },
  {
    key: "studio-mastering-metalcore",
    category: "mastering",
    title: { zh: "Modern Metalcore 錄音室母帶", en: "Modern metalcore studio master" },
    summary: { zh: "讓 Drop-tuned 吉他、Double Kick、低頻與嘶吼都清楚，保持重量但不要過度壓扁。", en: "Keeps down-tuned guitars, double kick, low end, and screams clear while retaining weight without flattening." },
    use: { zh: "Metalcore、重型搖滾、Breakdown 作品", en: "Metalcore, heavy rock, and breakdown-led tracks" },
    copy: { zh: "Modern metalcore, 150 BPM, C minor, powerful clean lead contrasting with controlled screamed accents, down-tuned guitars, palm-muted riffs, double-kick drums, sub bass, and atmospheric synths, tense verse into a huge half-time breakdown and melodic final chorus, lyrics about surviving betrayal, precise heavy mix, tight low end, clear kick-guitar separation, controlled aggression, loud but not crushed.", en: "Modern metalcore, 150 BPM, C minor, powerful clean lead contrasting with controlled screamed accents, down-tuned guitars, palm-muted riffs, double-kick drums, sub bass, and atmospheric synths, tense verse into a huge half-time breakdown and melodic final chorus, lyrics about surviving betrayal, precise heavy mix, tight low end, clear kick-guitar separation, controlled aggression, loud but not crushed." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["metalcore", "metal", "breakdown", "double kick", "重型", "嘶吼"],
  },
  {
    key: "studio-mastering-afrobeat",
    category: "mastering",
    title: { zh: "Afrobeat／Highlife 錄音室母帶", en: "Afrobeat / highlife studio master" },
    summary: { zh: "把多層打擊樂與交錯吉他整理成有呼吸的 Groove，保留人聲與舞動感。", en: "Organizes layered percussion and interlocking guitars into a breathing groove with clear vocal and movement." },
    use: { zh: "Afrobeat、Highlife、城市律動與陽光作品", en: "Afrobeat, highlife, urban groove, and sunlit tracks" },
    copy: { zh: "Afrobeat and highlife fusion, 108 BPM, A major, relaxed conversational lead with layered responses, interlocking electric guitars, syncopated bass, congas, shakers, talking-drum accents, and bright horn stabs, groove builds by adding percussion into a communal chorus, lyrics about freedom in the city, warm polished mix, natural transient punch, clear vocal, open stable stereo field.", en: "Afrobeat and highlife fusion, 108 BPM, A major, relaxed conversational lead with layered responses, interlocking electric guitars, syncopated bass, congas, shakers, talking-drum accents, and bright horn stabs, groove builds by adding percussion into a communal chorus, lyrics about freedom in the city, warm polished mix, natural transient punch, clear vocal, open stable stereo field." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["afrobeat", "highlife", "percussion", "groove", "非洲節奏", "城市律動"],
  },
  {
    key: "studio-mastering-taiwanese-pop",
    category: "mastering",
    title: { zh: "Modern Taiwanese Pop／台語流行錄音室母帶", en: "Modern Taiwanese pop studio master" },
    summary: { zh: "把台語咬字、主唱情緒與流行副歌放在最前面，保留現代樂團與電子層次。", en: "Puts Taiwanese diction, vocal emotion, and a memorable pop chorus first while retaining modern band and electronic layers." },
    use: { zh: "台語流行、在地故事、海邊與生活感作品", en: "Taiwanese pop, local storytelling, seaside themes, and everyday-life songs" },
    copy: { zh: "Modern Taiwanese pop, 96 BPM, F major, warm expressive lead with clear Taiwanese diction, piano and acoustic guitar support a melodic bass line, restrained live drums, subtle synth pads, and harmony responses, intimate verse into a memorable sing-along chorus, lyrics about returning to a seaside town, vocal-forward studio mix, controlled sibilance, smooth low mids, natural stereo width, preserved emotion.", en: "Modern Taiwanese pop, 96 BPM, F major, warm expressive lead with clear Taiwanese diction, piano and acoustic guitar support a melodic bass line, restrained live drums, subtle synth pads, and harmony responses, intimate verse into a memorable sing-along chorus, lyrics about returning to a seaside town, vocal-forward studio mix, controlled sibilance, smooth low mids, natural stereo width, preserved emotion." },
    evidence: "version",
    sources: STUDIO_SOURCES,
    keywords: ["taiwanese pop", "taiwanese", "台語", "台灣流行", "diction", "咬字"],
  },
];
