import type { SunoTechnique } from "./suno-practice-library.ts";

const SOUND_PROMPT_SOURCES = [
  "Suno Music Glossary",
  "Suno V4.5 Detailed Style Instructions",
  "AIPOGER Suno Songwriting Skill",
];

const MODEL_REFERENCE_SOURCES = [
  ...SOUND_PROMPT_SOURCES,
  "Suno Moderation FAQ",
];

// These are modular Style-field ingredients, not claims of exact hardware
// emulation. Named models are intentionally paired with audible traits so a
// creator can keep the sound direction even when Suno ignores or moderates a
// brand reference.
export const SUNO_INSTRUMENT_TONE_PROMPTS: SunoTechnique<"production">[] = [
  {
    key: "instrument-tone-drums-acoustic-kit",
    category: "production",
    title: { zh: "鼓｜經典近收音套鼓", en: "Drums | classic close-mic kit" },
    summary: { zh: "用 Kick、Snare、Toms 的工作分配先定義真鼓骨架；近收音讓節奏清楚，Room Mic 留一點現場呼吸。", en: "Defines a live drum foundation through kick, snare, and tom roles; close mics keep the groove clear while room ambience preserves breath." },
    use: { zh: "流行、Rock、Soul、Indie，需要真鼓但不能糊成一團", en: "Pop, rock, soul, and indie tracks that need live drums without a cloudy wall" },
    copy: { zh: "tight close-mic acoustic drum kit, solid kick, crisp snare crack, controlled toms, subtle overhead cymbal detail, small live-room ambience, drummer feels human and pocketed, punchy transients, clear vocal space", en: "tight close-mic acoustic drum kit, solid kick, crisp snare crack, controlled toms, subtle overhead cymbal detail, small live-room ambience, drummer feels human and pocketed, punchy transients, clear vocal space" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["drums", "acoustic kit", "close mic", "kick", "snare", "真鼓", "鼓組"],
  },
  {
    key: "instrument-tone-drums-808-909",
    category: "production",
    title: { zh: "鼓機｜808／909 經典電子底盤", en: "Drum machines | 808 / 909 foundation" },
    summary: { zh: "把 808 的圓厚低頻和 909 的硬朗 Kick、Hat 分開描述，適合電子、Hip-Hop 與跨界舞曲。", en: "Separates the round low end of an 808 from the harder kick and hats of a 909 for electronic, hip-hop, and hybrid dance work." },
    use: { zh: "需要經典電子鼓機味、Sub 要有記憶點時", en: "When a track needs recognizable drum-machine weight and memorable sub impact" },
    copy: { zh: "classic TR-808-style sub kick and clap layered with punchy TR-909-style kick, open hats and rides, clean step-sequenced groove, deep controlled low end, dry center image, bright but restrained top", en: "classic TR-808-style sub kick and clap layered with punchy TR-909-style kick, open hats and rides, clean step-sequenced groove, deep controlled low end, dry center image, bright but restrained top" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["808", "909", "drum machine", "kick", "clap", "電子鼓機", "電子音樂"],
  },
  {
    key: "instrument-tone-drums-gated-snare",
    category: "production",
    title: { zh: "鼓｜80 年代 Gated Snare", en: "Drums | gated 1980s snare" },
    summary: { zh: "用短而有衝擊的 Gate 殘響讓 Snare 在副歌或轉場跳出來，不把整首歌變成過度復古的效果展示。", en: "Uses a short, explosive gated tail to make the snare jump in choruses or transitions without turning the whole track into an era gimmick." },
    use: { zh: "Synthwave、New Wave、Arena Rock、復古流行副歌", en: "Synthwave, new wave, arena rock, and retro-pop choruses" },
    copy: { zh: "big gated snare, short explosive reverb tail, punchy 1980s live drums, bright tom fills, tight kick, restrained cymbal wash, chorus opens wider with neon retro impact", en: "big gated snare, short explosive reverb tail, punchy 1980s live drums, bright tom fills, tight kick, restrained cymbal wash, chorus opens wider with neon retro impact" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["gated snare", "80s", "synthwave", "new wave", "arena rock", "門控軍鼓", "復古"],
  },
  {
    key: "instrument-tone-drums-breakbeat",
    category: "production",
    title: { zh: "鼓｜Breakbeat 取樣碎拍", en: "Drums | sampled breakbeat" },
    summary: { zh: "用切碎的 Break、微小的人性 timing 與清楚的 Snare 反拍，做出會推進但不是機械四拍的鼓。", en: "Builds forward motion from chopped breaks, slight human timing, and a clear backbeat instead of a mechanical four-on-the-floor grid." },
    use: { zh: "Breaks、Drum & Bass、UK Bass、Indie Dance", en: "Breaks, drum & bass, UK bass, and indie dance" },
    copy: { zh: "chopped sampled breakbeat drums, crisp syncopated snare, ghost notes, shuffled hats, tight transient edits, subtle vinyl texture, bass leaves space for the break, energetic but human timing", en: "chopped sampled breakbeat drums, crisp syncopated snare, ghost notes, shuffled hats, tight transient edits, subtle vinyl texture, bass leaves space for the break, energetic but human timing" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["breakbeat", "breaks", "drum and bass", "UK bass", "ghost notes", "碎拍", "取樣"],
  },
  {
    key: "instrument-tone-guitar-clean-chime",
    category: "production",
    title: { zh: "電吉他｜Clean Chime 清亮分解", en: "Electric guitar | clean chime" },
    summary: { zh: "先說明清音、分解和弦與高頻閃爍，再用 Chorus 或短 Delay 補空間；比只寫『好聽電吉他』更容易得到角色。", en: "Specifies clean arpeggios and high-end shimmer first, then adds chorus or short delay for space; clearer than simply asking for a good electric guitar." },
    use: { zh: "Indie Pop、Jangle Rock、Dream Pop、明亮副歌", en: "Indie pop, jangle rock, dream pop, and bright choruses" },
    copy: { zh: "clean electric guitar, chiming arpeggios, glassy single-coil character, light compression, subtle chorus, short slapback delay, guitar answers the vocal between lines, bright but never brittle", en: "clean electric guitar, chiming arpeggios, glassy single-coil character, light compression, subtle chorus, short slapback delay, guitar answers the vocal between lines, bright but never brittle" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["electric guitar", "clean", "chime", "single coil", "chorus", "電吉他", "清音"],
  },
  {
    key: "instrument-tone-guitar-tube-breakup",
    category: "production",
    title: { zh: "電吉他｜Tube Amp 邊緣破音", en: "Electric guitar | tube-amp edge of breakup" },
    summary: { zh: "讓刷弦和重拍在力道變大時自然破音，保留手感與和弦細節，適合需要現場感的樂團編制。", en: "Lets strums and accents break up naturally when played harder, retaining touch and chord detail for a live-band feel." },
    use: { zh: "Alternative Rock、Blues、Country Rock、溫暖副歌", en: "Alternative rock, blues, country rock, and warm choruses" },
    copy: { zh: "edge-of-breakup tube amp electric guitar, warm midrange, dynamic pick attack, open chord strums, light overdrive that blooms on accents, spring reverb, guitar doubles the hook without masking the lead vocal", en: "edge-of-breakup tube amp electric guitar, warm midrange, dynamic pick attack, open chord strums, light overdrive that blooms on accents, spring reverb, guitar doubles the hook without masking the lead vocal" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["tube amp", "edge of breakup", "overdrive", "spring reverb", "alternative rock", "真空管", "破音"],
  },
  {
    key: "instrument-tone-guitar-high-gain",
    category: "production",
    title: { zh: "電吉他｜高增益牆與清楚 Riff", en: "Electric guitar | high-gain riff wall" },
    summary: { zh: "高增益不是把所有頻段塞滿；用雙層節奏吉他、清楚 Palm Mute 與中頻咬字保留 Riff 的輪廓。", en: "High gain should not fill every frequency; layered rhythm guitars, defined palm mutes, and midrange bite preserve the riff outline." },
    use: { zh: "Rock、Metal、Pop Punk、需要大副歌吉他牆時", en: "Rock, metal, pop punk, and large guitar-led choruses" },
    copy: { zh: "high-gain electric guitar wall, tightly double-tracked rhythm guitars, precise palm-muted riff, focused upper-mid bite, controlled feedback, melodic lead guitar answers the chorus, tight low end, no muddy distortion", en: "high-gain electric guitar wall, tightly double-tracked rhythm guitars, precise palm-muted riff, focused upper-mid bite, controlled feedback, melodic lead guitar answers the chorus, tight low end, no muddy distortion" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["high gain", "double tracked", "palm mute", "metal", "riff", "高增益", "吉他牆"],
  },
  {
    key: "instrument-tone-guitar-fuzz-shoegaze",
    category: "production",
    title: { zh: "電吉他｜Fuzz／Shoegaze 聲牆", en: "Electric guitar | fuzz shoegaze wall" },
    summary: { zh: "把 Fuzz、反饋與長殘響當成氛圍層，保留低頻中心與主唱位置，避免全曲只剩一團失真。", en: "Treats fuzz, feedback, and long reverb as an atmospheric layer while preserving the low-end center and vocal position." },
    use: { zh: "Shoegaze、Dream Pop、Post-Rock、迷幻段落", en: "Shoegaze, dream pop, post-rock, and psychedelic sections" },
    copy: { zh: "dense fuzz electric guitar, blooming feedback, reverse reverb swells, chorus-soaked tremolo picking, wide shoegaze guitar layers, vocal stays centered and intimate, soft kick anchor, hazy but defined stereo wall", en: "dense fuzz electric guitar, blooming feedback, reverse reverb swells, chorus-soaked tremolo picking, wide shoegaze guitar layers, vocal stays centered and intimate, soft kick anchor, hazy but defined stereo wall" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["fuzz", "shoegaze", "reverse reverb", "feedback", "dream pop", "失真", "音牆"],
  },
  {
    key: "instrument-tone-piano-grand",
    category: "production",
    title: { zh: "鋼琴｜近距離 Grand Piano 主體", en: "Piano | close grand piano anchor" },
    summary: { zh: "用大鋼琴承擔和聲與 Hook，補上踏板、擊鍵與自然 Room，讓它像演奏者而不是背景貼圖。", en: "Lets a grand piano carry harmony and hook with pedal, hammer, and natural room detail so it feels performed rather than pasted on." },
    use: { zh: "流行抒情、電影感、鋼琴主導的副歌", en: "Pop ballads, cinematic songs, and piano-led choruses" },
    copy: { zh: "expressive close grand piano, detailed hammer attack, warm low mids, natural sustain pedal, gentle room reflections, piano carries the chord movement and hook, intimate verse opens into a wider chorus", en: "expressive close grand piano, detailed hammer attack, warm low mids, natural sustain pedal, gentle room reflections, piano carries the chord movement and hook, intimate verse opens into a wider chorus" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["piano", "grand piano", "close piano", "ballad", "鋼琴", "大鋼琴"],
  },
  {
    key: "instrument-tone-piano-felt-upright",
    category: "production",
    title: { zh: "鋼琴｜Felt／Upright 私密琴房", en: "Piano | felt upright intimacy" },
    summary: { zh: "用柔和擊鍵、短 Room 與不過亮的高頻，讓鋼琴像在小房間裡陪著人聲，適合脆弱與回憶感。", en: "Uses softened hammers, short room reflections, and rounded highs for a piano that sits beside the vocal in a small room." },
    use: { zh: "Indie Folk、New Age、低語主歌、回憶感作品", en: "Indie folk, new age, whispered verses, and reflective songs" },
    copy: { zh: "felt upright piano, soft muted hammer tone, close-room recording, gentle pedal noise, rounded highs, sparse voicings leave space for an intimate lead vocal, subtle tape warmth, fragile and human", en: "felt upright piano, soft muted hammer tone, close-room recording, gentle pedal noise, rounded highs, sparse voicings leave space for an intimate lead vocal, subtle tape warmth, fragile and human" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["felt piano", "upright piano", "intimate", "close room", "Felt Piano", "立式鋼琴", "私密"],
  },
  {
    key: "instrument-tone-keys-rhodes",
    category: "production",
    title: { zh: "鍵盤｜Rhodes 電鋼琴 Pocket", en: "Keys | Rhodes pocket" },
    summary: { zh: "Rhodes 的重點是溫暖電氣顆粒、和弦色彩與 Groove 裡的讓位，不是把鍵盤彈得很滿。", en: "The point of Rhodes is warm electric grain, colorful voicings, and pocket—not a keyboard part that fills every gap." },
    use: { zh: "Soul、R&B、Neo-Soul、Jazz Pop", en: "Soul, R&B, neo-soul, and jazz pop" },
    copy: { zh: "Rhodes-style electric piano, warm bell-like tine tone, rich seventh and ninth chords, slightly behind-the-beat comping, gentle tremolo, rounded low mids, leaves pockets for the vocal and bass", en: "Rhodes-style electric piano, warm bell-like tine tone, rich seventh and ninth chords, slightly behind-the-beat comping, gentle tremolo, rounded low mids, leaves pockets for the vocal and bass" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["Rhodes", "electric piano", "neo soul", "seventh chords", "電鋼琴", "和弦色彩"],
  },
  {
    key: "instrument-tone-keys-hammond",
    category: "production",
    title: { zh: "鍵盤｜Hammond Organ 與 Leslie 流動", en: "Keys | Hammond organ and Leslie motion" },
    summary: { zh: "讓 Hammond 承擔和聲厚度與副歌抬升，Leslie 旋轉只做流動感，不搶走主唱與鼓的中心。", en: "Uses Hammond for harmonic weight and chorus lift, with Leslie motion adding movement without stealing the center from vocal or drums." },
    use: { zh: "Gospel、Soul、Rock、復古現場樂團", en: "Gospel, soul, rock, and vintage live-band arrangements" },
    copy: { zh: "Hammond B3-style organ, warm drawbar chorus, subtle Leslie rotary movement, sustained chords cushion the vocal, tasteful gospel swells into the chorus, live-room band feel, rich but controlled low mids", en: "Hammond B3-style organ, warm drawbar chorus, subtle Leslie rotary movement, sustained chords cushion the vocal, tasteful gospel swells into the chorus, live-room band feel, rich but controlled low mids" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["Hammond", "B3", "Leslie", "organ", "gospel", "風琴", "教會風琴"],
  },
  {
    key: "instrument-tone-synth-minimoog-bass",
    category: "production",
    title: { zh: "合成器｜Moog 風格單音 Bass", en: "Synth | Moog-style mono bass" },
    summary: { zh: "用單音、鋸齒波、濾波器滑動與短 Envelope 把 Sub Bass 做成會說話的 Hook，而不是一條平直低音。", en: "Turns sub bass into a speaking hook through monophonic saw tone, filter movement, and a short envelope instead of a flat low line." },
    use: { zh: "Synthwave、Electro、House、Bass Music", en: "Synthwave, electro, house, and bass music" },
    copy: { zh: "Moog Minimoog Model D-inspired mono synth bass, warm sawtooth oscillator, resonant low-pass filter sweep, short punchy envelope, subtle glide, bass locks tightly with the kick, centered mono sub with audible midrange growl", en: "Moog Minimoog Model D-inspired mono synth bass, warm sawtooth oscillator, resonant low-pass filter sweep, short punchy envelope, subtle glide, bass locks tightly with the kick, centered mono sub with audible midrange growl" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["Moog", "Minimoog", "Model D", "mono synth", "synth bass", "合成器 Bass", "Sub"],
  },
  {
    key: "instrument-tone-synth-juno-pad",
    category: "production",
    title: { zh: "合成器｜Juno 風格 Chorus Pad", en: "Synth | Juno-style chorus pad" },
    summary: { zh: "用雙振盪器、柔和濾波與寬 Chorus 做出會托住副歌的類比 Pad，保留中央人聲空間。", en: "Builds an analog-style pad from dual oscillators, a soft filter, and wide chorus while leaving a clear center for vocals." },
    use: { zh: "Dream Pop、Synth Pop、House、80 年代氛圍", en: "Dream pop, synth pop, house, and 1980s atmospheres" },
    copy: { zh: "Roland Juno-style poly synth pad, warm dual oscillators, soft low-pass filter, lush stereo chorus, slow attack and release, gently pulsing chord bed, wide sides with a clean mono center for the lead vocal", en: "Roland Juno-style poly synth pad, warm dual oscillators, soft low-pass filter, lush stereo chorus, slow attack and release, gently pulsing chord bed, wide sides with a clean mono center for the lead vocal" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["Juno", "synth", "poly synth", "pad", "chorus", "synth pop", "類比 Pad", "寬聲場"],
  },
  {
    key: "instrument-tone-synth-prophet-lead",
    category: "production",
    title: { zh: "合成器｜Prophet 風格寬和弦與 Lead", en: "Synth | Prophet-style poly chords" },
    summary: { zh: "用失諧雙振盪器與有重量的濾波，讓和弦與 Lead 有復古合成器的厚度，同時限制聲部數避免混音過滿。", en: "Uses detuned oscillators and a weighty filter for vintage poly-synth depth, while limiting density so the mix does not fill up." },
    use: { zh: "Indie Dance、Synthwave、復古 Pop、電影感電子", en: "Indie dance, synthwave, retro pop, and cinematic electronic music" },
    copy: { zh: "Prophet-5-style analog poly synth, slightly detuned oscillators, rich saw and pulse blend, warm resonant filter, slow evolving attack, wide chord stabs and a restrained melodic lead, tape-softened top end", en: "Prophet-5-style analog poly synth, slightly detuned oscillators, rich saw and pulse blend, warm resonant filter, slow evolving attack, wide chord stabs and a restrained melodic lead, tape-softened top end" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["Prophet", "Prophet-5", "analog synth", "polyphonic", "synthwave", "類比合成器", "和弦"],
  },
  {
    key: "instrument-tone-synth-dx7-fm",
    category: "production",
    title: { zh: "合成器｜DX7 風格 FM 電鋼琴", en: "Synth | DX7-style FM keys" },
    summary: { zh: "用 FM 的玻璃感、金屬泛音與明確起音，讓鍵盤在 R&B、Pop 或復古舞曲裡穿透但不刺耳。", en: "Uses FM glass, metallic overtones, and a defined attack so the keys cut through R&B, pop, or retro dance without harshness." },
    use: { zh: "80 年代 Pop、R&B、City Pop、Funk 鍵盤", en: "1980s pop, R&B, city pop, and funk keys" },
    copy: { zh: "Yamaha DX7-style FM electric piano, glassy bell-like attack, clean digital overtones, gentle chorus, syncopated chord stabs, controlled upper mids, leaves room for the vocal and bass groove", en: "Yamaha DX7-style FM electric piano, glassy bell-like attack, clean digital overtones, gentle chorus, syncopated chord stabs, controlled upper mids, leaves room for the vocal and bass groove" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["DX7", "FM", "electric piano", "city pop", "digital", "FM 合成", "玻璃感"],
  },
  {
    key: "instrument-tone-synth-303-acid",
    category: "production",
    title: { zh: "合成器｜303 Acid 滑音 Bassline", en: "Synth | 303 acid bassline" },
    summary: { zh: "用單音滑音、Accent 與 Resonance 讓 Bassline 自己成為主角；鼓與主唱必須留下清楚位置。", en: "Makes the bassline the hook through slides, accents, and resonance while keeping clear space for drums and vocals." },
    use: { zh: "Acid House、Acid Techno、Electro、Rave", en: "Acid house, acid techno, electro, and rave" },
    copy: { zh: "TB-303-style acid bassline, squelchy resonant low-pass filter, expressive slides and accented notes, repetitive hypnotic pattern, gradually opening cutoff into the drop, dry punchy kick, mono-centered low end", en: "TB-303-style acid bassline, squelchy resonant low-pass filter, expressive slides and accented notes, repetitive hypnotic pattern, gradually opening cutoff into the drop, dry punchy kick, mono-centered low end" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["303", "acid", "acid house", "acid techno", "resonance", "滑音", "酸性"],
  },
  {
    key: "instrument-tone-bass-p-bass",
    category: "production",
    title: { zh: "Bass｜P Bass 溫厚根音", en: "Bass | P-bass root weight" },
    summary: { zh: "讓 Bass 鎖定 Kick、用圓厚中低頻撐住和聲，適合需要穩定而不搶戲的樂團低頻。", en: "Locks bass to the kick and supports harmony with rounded low mids for a band low end that stays steady without taking over." },
    use: { zh: "Rock、Pop、Soul、Motown、Band 編制", en: "Rock, pop, soul, Motown, and band arrangements" },
    copy: { zh: "Fender Precision Bass-style electric bass, round focused low mids, warm fingerstyle thump, simple melodic root movement, bass locks with the kick and supports the guitar riff, controlled sub, natural amp warmth", en: "Fender Precision Bass-style electric bass, round focused low mids, warm fingerstyle thump, simple melodic root movement, bass locks with the kick and supports the guitar riff, controlled sub, natural amp warmth" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["bass", "P Bass", "Precision Bass", "electric bass", "Motown", "fingerstyle", "電貝斯", "根音"],
  },
  {
    key: "instrument-tone-bass-j-bass-funk",
    category: "production",
    title: { zh: "Bass｜J Bass Funk 彈性線條", en: "Bass | J-bass funk movement" },
    summary: { zh: "用清楚的指彈起音、滑音與高頻彈性讓 Bassline 參與 Groove，但低頻仍保持乾淨。", en: "Uses finger attack, slides, and upper-mid articulation to make the bassline part of the groove while keeping the low end clean." },
    use: { zh: "Funk、Disco、R&B、Indie Dance", en: "Funk, disco, R&B, and indie dance" },
    copy: { zh: "Fender Jazz Bass-style electric bass, articulate fingerstyle attack, elastic funky syncopation, tasteful slides and ghost notes, bright bridge-pickup bite, tight kick-bass pocket, controlled sub and lively midrange", en: "Fender Jazz Bass-style electric bass, articulate fingerstyle attack, elastic funky syncopation, tasteful slides and ghost notes, bright bridge-pickup bite, tight kick-bass pocket, controlled sub and lively midrange" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["J Bass", "Jazz Bass", "funk", "disco", "ghost notes", "放克 Bass", "彈性"],
  },
  {
    key: "instrument-tone-bass-upright-jazz",
    category: "production",
    title: { zh: "Bass｜Upright Jazz 走動低音", en: "Bass | upright jazz walking bass" },
    summary: { zh: "用木質共鳴、手指起音與走動根音支撐 Jazz／Bossa；低頻要暖但不能拖慢整個 Groove。", en: "Supports jazz or bossa with woody resonance, finger attack, and walking roots while keeping the groove buoyant." },
    use: { zh: "Jazz、Bossa、Lounge、爵士流行", en: "Jazz, bossa, lounge, and jazz-pop" },
    copy: { zh: "warm upright double bass, woody finger attack, walking bass movement, subtle fingerboard resonance, lightly muted room, bass supports brushed drums and piano without boomy sub", en: "warm upright double bass, woody finger attack, walking bass movement, subtle fingerboard resonance, lightly muted room, bass supports brushed drums and piano without boomy sub" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["upright bass", "double bass", "walking bass", "jazz", "bossa", "低音提琴", "走動低音"],
  },
  {
    key: "instrument-tone-bass-reese-sub",
    category: "production",
    title: { zh: "Bass｜Reese／Sub Bass 流動低頻", en: "Bass | Reese and sub movement" },
    summary: { zh: "用輕微失諧、濾波運動與 Mono Sub 做出 D&B、Dubstep 常見的流動低頻，避免低頻寬到失去中心。", en: "Uses slight detuning, filter motion, and a mono sub center for moving D&B or dubstep low end without losing focus." },
    use: { zh: "Drum & Bass、Dubstep、UK Bass、暗黑電子", en: "Drum & bass, dubstep, UK bass, and dark electronic music" },
    copy: { zh: "deep Reese bass, subtly detuned saw layers, moving low-pass filter, gritty mid-bass growl above a stable mono sub, bass answers the breakbeat, kick-sub separation stays clear, dark spacious mix", en: "deep Reese bass, subtly detuned saw layers, moving low-pass filter, gritty mid-bass growl above a stable mono sub, bass answers the breakbeat, kick-sub separation stays clear, dark spacious mix" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["Reese bass", "sub bass", "drum and bass", "dubstep", "mono sub", "流動低頻", "深層 Bass"],
  },
  {
    key: "instrument-tone-mic-u87-vocal",
    category: "production",
    title: { zh: "麥克風｜大型電容人聲近收音", en: "Microphone | large-diaphragm vocal condenser" },
    summary: { zh: "品牌只當音色方向：重點是近距離、細節、平順高頻與穩定的主唱中心，不宣稱 Suno 會還原實體麥克風。", en: "Treats the brand as a tonal direction only: close detail, smooth highs, and a stable vocal center matter more than exact hardware recreation." },
    use: { zh: "Pop、Ballad、R&B、需要主唱在最前面時", en: "Pop, ballads, R&B, and any track that needs a forward lead vocal" },
    copy: { zh: "Neumann U87-style large-diaphragm condenser vocal tone, intimate close-mic detail, smooth controlled presence, natural proximity warmth, clear consonants, centered lead vocal, gentle room depth, polished but not hyped", en: "Neumann U87-style large-diaphragm condenser vocal tone, intimate close-mic detail, smooth controlled presence, natural proximity warmth, clear consonants, centered lead vocal, gentle room depth, polished but not hyped" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["U87", "Neumann", "condenser", "microphone", "vocal mic", "close mic", "電容麥克風", "主唱"],
  },
  {
    key: "instrument-tone-mic-sm57-guitar",
    category: "production",
    title: { zh: "麥克風｜動圈近收音吉他音箱", en: "Microphone | dynamic guitar-cab close mic" },
    summary: { zh: "把 SM57 類方向翻成可聽特徵：近距離、快速起音、中頻咬字與清楚的音箱邊緣，適合電吉他與 Snare。", en: "Translates an SM57-like direction into audible traits: close perspective, fast attack, midrange bite, and defined amp edge for guitar or snare." },
    use: { zh: "電吉他 Riff、Rock Snare、需要清楚起音時", en: "Electric-guitar riffs, rock snares, and sources that need defined attack" },
    copy: { zh: "SM57-style dynamic close-mic guitar cabinet tone, focused midrange bite, fast pick transient, controlled proximity, slightly gritty amp edge, double-tracked guitars stay separated, punchy and direct", en: "SM57-style dynamic close-mic guitar cabinet tone, focused midrange bite, fast pick transient, controlled proximity, slightly gritty amp edge, double-tracked guitars stay separated, punchy and direct" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["SM57", "dynamic mic", "guitar cab", "snare", "close mic", "動圈麥克風", "音箱"],
  },
  {
    key: "instrument-tone-mic-ribbon-room",
    category: "production",
    title: { zh: "麥克風｜Ribbon 柔暗房間感", en: "Microphone | ribbon warmth and room" },
    summary: { zh: "用 Ribbon 的柔和高頻、厚中頻與自然 Room 取代刺耳亮度，適合吉他、銅管、房間鼓與復古人聲方向。", en: "Uses soft highs, thick mids, and natural room depth instead of brittle brightness for guitar, brass, room drums, or vintage vocals." },
    use: { zh: "復古錄音、Blues、Jazz、溫暖房間鼓與銅管", en: "Vintage recording, blues, jazz, warm room drums, and brass" },
    copy: { zh: "ribbon microphone-inspired tone, smooth dark high end, thick natural midrange, gentle proximity warmth, room microphone perspective, soft transient edges, vintage analog character without muffling the arrangement", en: "ribbon microphone-inspired tone, smooth dark high end, thick natural midrange, gentle proximity warmth, room microphone perspective, soft transient edges, vintage analog character without muffling the arrangement" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["ribbon mic", "room mic", "vintage", "dark highs", "brass", "鋁帶麥克風", "房間感"],
  },
  {
    key: "instrument-tone-recording-di-room",
    category: "production",
    title: { zh: "收音｜DI、音箱與 Room 三層", en: "Recording | DI, amp, and room layers" },
    summary: { zh: "把直接聲、音箱聲與房間聲分成角色，讓樂器既有起音又有空間；這比只寫一個麥克風品牌更穩。", en: "Gives direct, amp, and room signals separate jobs so an instrument has both attack and space; this is usually steadier than naming one microphone." },
    use: { zh: "Bass、電吉他、現場樂團與想要真實空間時", en: "Bass, electric guitar, live bands, and realistic room perspectives" },
    copy: { zh: "layered recording perspective: clean DI attack, warm miked amplifier body, subtle live-room microphone ambience, phase-coherent center, instrument remains articulate under the vocal, natural bleed and human dynamics", en: "layered recording perspective: clean DI attack, warm miked amplifier body, subtle live-room microphone ambience, phase-coherent center, instrument remains articulate under the vocal, natural bleed and human dynamics" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["DI", "amp", "room", "recording", "live room", "直接聲", "音箱", "收音"],
  },
  {
    key: "instrument-tone-effect-1176-vocal",
    category: "production",
    title: { zh: "效果｜1176 風格快速人聲壓縮", en: "Effects | 1176-style vocal compression" },
    summary: { zh: "用快速 Attack、穩定字頭與帶一點前推感描述壓縮，不把它當成精確外掛設定。", en: "Describes fast attack, stable consonants, and a little forward push without pretending to specify an exact plugin setting." },
    use: { zh: "Pop、Rock、Rap、需要人聲穩定靠前時", en: "Pop, rock, rap, and vocals that need a stable forward position" },
    copy: { zh: "1176-style fast vocal compression, controlled peaks, clear consonant attack, slightly forward and energetic lead, audible breath detail, parallel compression lift in the chorus, natural dynamics preserved", en: "1176-style fast vocal compression, controlled peaks, clear consonant attack, slightly forward and energetic lead, parallel compression lift in the chorus, natural dynamics preserved" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["1176", "compressor", "vocal compression", "parallel compression", "人聲壓縮", "快速 Attack"],
  },
  {
    key: "instrument-tone-effect-la2a-vocal",
    category: "production",
    title: { zh: "效果｜LA-2A 風格柔順人聲", en: "Effects | LA-2A-style vocal leveling" },
    summary: { zh: "用光學式的柔順、長一點的呼吸與貼近感處理主唱，適合抒情、Soul 與不想太硬的聲音。", en: "Uses smooth optical-style leveling and a breathing, intimate feel for ballads, soul, and vocals that should not sound aggressively clamped." },
    use: { zh: "Ballad、Soul、Jazz、柔和女聲或男聲", en: "Ballads, soul, jazz, and softer male or female vocals" },
    copy: { zh: "LA-2A-style optical vocal leveling, smooth even phrasing, gentle tube warmth, intimate sustained notes, rounded transients, soft de-essed presence, vocal stays calm and close above the arrangement", en: "LA-2A-style optical vocal leveling, smooth even phrasing, gentle tube warmth, intimate sustained notes, rounded transients, soft de-essed presence, vocal stays calm and close above the arrangement" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["LA-2A", "optical compressor", "leveling", "tube warmth", "vocal", "光學壓縮", "柔順"],
  },
  {
    key: "instrument-tone-effect-tape-echo",
    category: "production",
    title: { zh: "效果｜Tape Echo 復古延遲", en: "Effects | tape echo delay" },
    summary: { zh: "用 Tape 的衰減、微小 Wow & Flutter 與回授控制做空間尾巴，讓延遲跟著節奏退場，不蓋住歌詞。", en: "Uses tape decay, subtle wow and flutter, and controlled feedback so echoes leave with the groove instead of covering the lyric." },
    use: { zh: "Dub、Rockabilly、Synthwave、主唱或吉他轉場", en: "Dub, rockabilly, synthwave, and vocal or guitar transitions" },
    copy: { zh: "Echoplex-style tape echo, warm repeating delay, subtle wow and flutter, filtered repeats that darken over time, controlled feedback throws on phrase endings, dry lead remains clear in the center", en: "Echoplex-style tape echo, warm repeating delay, subtle wow and flutter, filtered repeats that darken over time, controlled feedback throws on phrase endings, dry lead remains clear in the center" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["tape echo", "Echoplex", "delay", "wow flutter", "dub", "磁帶延遲", "回授"],
  },
  {
    key: "instrument-tone-effect-plate-hall",
    category: "production",
    title: { zh: "效果｜Plate 與 Hall 分工空間", en: "Effects | plate and hall reverb roles" },
    summary: { zh: "Plate 讓人聲與 Snare 有亮度，Hall 給副歌與弦樂更大的遠景；明確分工比整首加 Heavy Reverb 更乾淨。", en: "Plate adds sheen to vocals and snare while hall gives choruses or strings a larger horizon; defined roles are cleaner than heavy reverb everywhere." },
    use: { zh: "流行人聲、鼓組、弦樂與電影感副歌", en: "Pop vocals, drums, strings, and cinematic choruses" },
    copy: { zh: "short plate reverb on lead vocal and snare for presence, longer cinematic hall behind chorus strings and pads, pre-delay keeps lyrics clear, reverb blooms between phrases, centered dry vocal with controlled depth", en: "short plate reverb on lead vocal and snare for presence, longer cinematic hall behind chorus strings and pads, pre-delay keeps lyrics clear, reverb blooms between phrases, centered dry vocal with controlled depth" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["plate reverb", "hall reverb", "pre-delay", "vocal space", "混響", "板式", "Hall"],
  },
  {
    key: "instrument-tone-effect-chorus-phaser",
    category: "production",
    title: { zh: "效果｜Chorus／Phaser 流動寬度", en: "Effects | chorus and phaser movement" },
    summary: { zh: "用 Chorus 做厚度、Phaser 做慢速移動；效果放在 Pad、吉他或背景聲部，主唱與低頻保持穩定。", en: "Uses chorus for thickness and phaser for slow movement on pads, guitars, or background parts while vocal and low end stay stable." },
    use: { zh: "Dream Pop、Disco、Funk、Synthwave、復古鍵盤", en: "Dream pop, disco, funk, synthwave, and retro keys" },
    copy: { zh: "subtle analog chorus and slow phaser movement on electric guitar and synth pads, lush but controlled stereo width, modulation stays out of the mono low end, lead vocal remains centered and focused", en: "subtle analog chorus and slow phaser movement on electric guitar and synth pads, lush but controlled stereo width, modulation stays out of the mono low end, lead vocal remains centered and focused" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["chorus", "phaser", "modulation", "stereo width", "Dream Pop", "相位", "寬度"],
  },
  {
    key: "instrument-tone-mix-analog-console",
    category: "production",
    title: { zh: "混音｜Analog Console 溫暖膠水", en: "Mix | analog console glue" },
    summary: { zh: "把 Console 味翻成輕微飽和、穩定中頻與自然串音；它是整體質感方向，不代表真的經過某張實體控台。", en: "Translates console color into gentle saturation, stable mids, and natural cohesion; it is a mix direction, not proof of a specific physical console." },
    use: { zh: "想要樂團一起演奏的黏著感、復古 Pop 或 Soul", en: "Band cohesion, retro pop, and soul mixes that need a played-together feel" },
    copy: { zh: "warm analog console-style mix, gentle channel saturation, cohesive midrange, subtle console crosstalk, punchy but rounded transients, instruments feel recorded together, vocal remains clear, low end stays controlled", en: "warm analog console-style mix, gentle channel saturation, cohesive midrange, subtle console crosstalk, punchy but rounded transients, instruments feel recorded together, vocal remains clear, low end stays controlled" },
    evidence: "version",
    sources: MODEL_REFERENCE_SOURCES,
    keywords: ["analog console", "console glue", "saturation", "mix", "混音", "類比膠水", "飽和"],
  },
  {
    key: "instrument-tone-mix-vocal-forward",
    category: "production",
    title: { zh: "混音｜主唱在前、樂器各就各位", en: "Mix | vocal-forward balance" },
    summary: { zh: "把主唱中心、樂器側邊與低頻留位說清楚，適合流行與需要歌詞第一時間被聽見的作品。", en: "Makes the vocal center, instrument sides, and low-end space explicit for songs where the lyric must be heard immediately." },
    use: { zh: "Pop、R&B、Rap、廣告歌與短影音 Hook", en: "Pop, R&B, rap, advertising songs, and short-form hooks" },
    copy: { zh: "vocal-forward modern mix, clear centered lead vocal, instruments arranged around the singer, kick and bass share a tight center, guitars and pads widen to the sides, crisp diction, smooth de-essed highs, polished but not over-limited", en: "vocal-forward modern mix, clear centered lead vocal, instruments arranged around the singer, kick and bass share a tight center, guitars and pads widen to the sides, crisp diction, smooth de-essed highs, polished but not over-limited" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["vocal forward", "center vocal", "stereo", "pop mix", "主唱靠前", "人聲中心", "清晰咬字"],
  },
  {
    key: "instrument-tone-mix-kick-sub",
    category: "production",
    title: { zh: "混音｜Kick／Sub 分離與 Mono 中心", en: "Mix | kick-sub separation" },
    summary: { zh: "讓 Kick 的起音與 Sub 的延音分工，低頻維持 Mono 中心，上方效果才負責寬度。", en: "Gives the kick attack and sub sustain separate jobs, keeping low frequencies mono-centered while upper effects provide width." },
    use: { zh: "House、Techno、Trap、Drum & Bass、任何低頻主導作品", en: "House, techno, trap, drum & bass, and any low-end-led track" },
    copy: { zh: "precise kick and sub-bass separation, short punchy kick attack, sustained mono sub, bass ducks naturally around the kick, controlled low mids, wide synths stay above the low-end center, club-ready but dynamic", en: "precise kick and sub-bass separation, short punchy kick attack, sustained mono sub, bass ducks naturally around the kick, controlled low mids, wide synths stay above the low-end center, club-ready but dynamic" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["kick", "sub bass", "mono", "sidechain", "club mix", "低頻分離", "低頻中心"],
  },
  {
    key: "instrument-tone-mix-wide-mono-safe",
    category: "production",
    title: { zh: "混音｜寬聲場但 Mono 不塌", en: "Mix | wide but mono-safe" },
    summary: { zh: "把寬度放在高頻 Pad、Delay 與背景聲，主唱、Kick、Bass 留在中心，讓手機與單聲道播放仍有骨架。", en: "Puts width in upper pads, delays, and background layers while vocal, kick, and bass stay centered for a stable mono and phone translation." },
    use: { zh: "電子、Pop、Dream Pop、需要大聲場但不能失焦時", en: "Electronic, pop, dream pop, and wide mixes that still need focus" },
    copy: { zh: "wide controlled stereo field, mono-compatible kick bass and lead vocal, spacious pads and delays on the sides, stable center image, phase-safe low end, depth through contrast rather than endless reverb", en: "wide controlled stereo field, mono-compatible kick bass and lead vocal, spacious pads and delays on the sides, stable center image, phase-safe low end, depth through contrast rather than endless reverb" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["wide stereo", "mono compatible", "phase safe", "stereo field", "寬聲場", "單聲道", "相位"],
  },
  {
    key: "instrument-tone-mix-tape-glue",
    category: "production",
    title: { zh: "混音｜Tape Saturation 膠合與圓角", en: "Mix | tape saturation glue" },
    summary: { zh: "用輕微 Tape 壓縮、諧波與高頻圓角把聲部黏起來；不要把『暖』寫成失去瞬態與細節。", en: "Uses gentle tape compression, harmonics, and softened highs to bind the parts without turning 'warm' into lost transients and detail." },
    use: { zh: "復古 Pop、Lo-Fi、Synthwave、想減少數位尖銳感時", en: "Retro pop, lo-fi, synthwave, or mixes that need less digital sharpness" },
    copy: { zh: "gentle tape saturation across the mix, subtle harmonic glue, rounded high frequencies, slightly softened transients, preserved drum punch and vocal detail, warm cohesive stereo image, no muddy low mids", en: "gentle tape saturation across the mix, subtle harmonic glue, rounded high frequencies, slightly softened transients, preserved drum punch and vocal detail, warm cohesive stereo image, no muddy low mids" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["tape saturation", "tape glue", "warm", "lo-fi", "analog", "磁帶飽和", "圓潤"],
  },
  {
    key: "instrument-tone-mix-polished-dynamic-master",
    category: "production",
    title: { zh: "混音｜拋光但保留動態的完成度", en: "Mix | polished but dynamic finish" },
    summary: { zh: "用可聽見的完成度描述母帶方向：低頻穩、瞬態保留、高頻順、主唱清楚；不把 Loudness 寫成越大越好。", en: "Describes a finished master through stable lows, preserved transients, smooth highs, and clear vocal rather than treating louder as automatically better." },
    use: { zh: "所有準備發表、上傳或做 Drop 的作品最後一輪方向", en: "The final direction for tracks headed to release, upload, or a Drop" },
    copy: { zh: "polished release-ready mix, clear lead vocal, controlled sub and low mids, punchy preserved transients, smooth de-essed highs, coherent stereo depth, balanced dynamics, clean headroom, loud enough without crushed drums or harsh clipping", en: "polished release-ready mix, clear lead vocal, controlled sub and low mids, punchy preserved transients, smooth de-essed highs, coherent stereo depth, balanced dynamics, clean headroom, loud enough without crushed drums or harsh clipping" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["master", "mastering", "release-ready", "dynamics", "headroom", "母帶", "完成度"],
  },
  {
    key: "instrument-tone-acoustic-guitar-fingerpicked",
    category: "production",
    title: { zh: "木吉他｜Fingerpicked 細節脈衝", en: "Acoustic guitar | fingerpicked pulse" },
    summary: { zh: "用指彈起音、弦噪與近距離木頭共鳴建立主歌脈衝，讓木吉他有角色而不是一層模糊伴奏。", en: "Builds a verse pulse from finger attack, string noise, and close wooden resonance so acoustic guitar has a role instead of becoming a blurry bed." },
    use: { zh: "Indie Folk、Singer-Songwriter、Pop 主歌與自然系編曲", en: "Indie folk, singer-songwriter, pop verses, and organic arrangements" },
    copy: { zh: "close-mic steel-string acoustic guitar, detailed fingerpicked attack, natural string squeaks, warm wooden resonance, alternating bass notes carry the pulse, sparse open voicings leave room for an intimate vocal", en: "close-mic steel-string acoustic guitar, detailed fingerpicked attack, natural string squeaks, warm wooden resonance, alternating bass notes carry the pulse, sparse open voicings leave room for an intimate vocal" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["acoustic guitar", "steel string", "fingerpicked", "singer songwriter", "木吉他", "指彈"],
  },
  {
    key: "instrument-tone-strings-cello-bed",
    category: "production",
    title: { zh: "弦樂｜Cello 低音線與 String Pad", en: "Strings | cello line and string pad" },
    summary: { zh: "讓 Cello 負責反線、String Pad 負責和聲床；先控制進場段落，避免弦樂從第一秒就把情緒用完。", en: "Gives cello the counterline and the string pad the harmonic bed, with sectional entrances that save emotional lift for later." },
    use: { zh: "電影感 Pop、抒情歌、交響流行與 Final Chorus", en: "Cinematic pop, ballads, symphonic pop, and final choruses" },
    copy: { zh: "warm cello counterline beneath the vocal, soft legato string pad enters in the pre-chorus, rising violins widen the final chorus, restrained pizzicato transition, natural bow detail, cinematic but emotionally spacious", en: "warm cello counterline beneath the vocal, soft legato string pad enters in the pre-chorus, rising violins widen the final chorus, restrained pizzicato transition, natural bow detail, cinematic but emotionally spacious" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["cello", "strings", "string pad", "legato", "pizzicato", "弦樂", "大提琴"],
  },
  {
    key: "instrument-tone-brass-sax-section",
    category: "production",
    title: { zh: "銅管／Sax｜回答句與副歌撞擊", en: "Brass and sax | replies and chorus hits" },
    summary: { zh: "用短回答句、Unison Stabs 或一段 Sax Solo 給歌手對話，不讓銅管整首持續轟鳴。", en: "Uses short replies, unison stabs, or a sax solo to converse with the vocal instead of letting brass roar continuously." },
    use: { zh: "Funk、Soul、Jazz Pop、Disco 與大副歌", en: "Funk, soul, jazz pop, disco, and big choruses" },
    copy: { zh: "tight brass section stabs answer the vocal, warm tenor sax fills between phrases, short unison hits lift the chorus, controlled room ambience, punchy midrange, brass stays rhythmic and never masks the lead", en: "tight brass section stabs answer the vocal, warm tenor sax fills between phrases, short unison hits lift the chorus, controlled room ambience, punchy midrange, brass stays rhythmic and never masks the lead" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["brass", "saxophone", "tenor sax", "horn section", "funk", "銅管", "薩克斯風"],
  },
  {
    key: "instrument-tone-percussion-hand-groove",
    category: "production",
    title: { zh: "手打擊樂｜Shaker、Conga、Clave 層次", en: "Hand percussion | shaker, conga, clave" },
    summary: { zh: "先讓主鼓負責骨架，再用 Shaker、Conga、Clave 補微小推進與文化節奏，不把所有打擊樂同時開滿。", en: "Lets the main kit carry the skeleton, then adds shaker, conga, and clave for small forward motion and cultural groove without overfilling the grid." },
    use: { zh: "Latin、Afro House、Amapiano、Disco、夏日與舞蹈作品", en: "Latin, Afro house, amapiano, disco, summer tracks, and dance music" },
    copy: { zh: "layered hand percussion, dry shaker pulse, syncopated conga replies, clear clave accents, main kick stays dominant, human swing and small timing variations, detailed high percussion, warm spacious groove", en: "layered hand percussion, dry shaker pulse, syncopated conga replies, clear clave accents, main kick stays dominant, human swing and small timing variations, detailed high percussion, warm spacious groove" },
    evidence: "field",
    sources: SOUND_PROMPT_SOURCES,
    keywords: ["hand percussion", "shaker", "conga", "clave", "afro house", "手打擊樂", "康加鼓", "Clave"],
  },
];
