export type SunoStudioMasteringAudioPreview = {
  key: string;
  audioUrl: string;
};

// Only audited, Prompt-linked Suno generations belong here. Beatport expansion
// assets stay out until each clip has a real source-generation record and a
// human listening check; file existence alone is not enough to publish audio.
const SUNO_STUDIO_MASTERING_AUDIO_PREVIEW_ASSETS = [
  ["studio-mastering-general", "general"],
  ["studio-mastering-acoustic-folk", "acoustic-folk"],
  ["studio-mastering-piano-pop", "piano-pop"],
  ["studio-mastering-dream-pop", "dream-pop"],
  ["studio-mastering-alt-rock", "alt-rock"],
  ["studio-mastering-pop-punk", "pop-punk"],
  ["studio-mastering-neo-soul", "neo-soul"],
  ["studio-mastering-hip-hop-trap", "hip-hop-trap"],
  ["studio-mastering-vocal-jazz", "vocal-jazz"],
  ["studio-mastering-nu-disco", "nu-disco"],
  ["studio-mastering-deep-house", "deep-house"],
  ["studio-mastering-melodic-techno", "melodic-techno"],
  ["studio-mastering-uplifting-trance", "uplifting-trance"],
  ["studio-mastering-liquid-dnb", "liquid-dnb"],
  ["studio-mastering-synthwave", "synthwave"],
  ["studio-mastering-orchestral-pop", "orchestral-pop"],
  ["studio-mastering-metalcore", "metalcore"],
  ["studio-mastering-afrobeat", "afrobeat-highlife"],
  ["studio-mastering-big-band-swing", "big-band-swing"],
  ["studio-mastering-bebop-hard-bop", "bebop-hard-bop"],
  ["studio-mastering-cool-jazz", "cool-jazz"],
  ["studio-mastering-bossa-nova-jazz", "bossa-nova-jazz"],
  ["studio-mastering-jazz-fusion", "jazz-fusion"],
  ["studio-mastering-acid-jazz", "acid-jazz"],
  ["studio-mastering-1950s-rockabilly", "1950s-rockabilly"],
  ["studio-mastering-1960s-motown-soul", "1960s-motown-soul"],
  ["studio-mastering-1960s-psychedelic-rock", "1960s-psychedelic-rock"],
  ["studio-mastering-1970s-soft-rock", "1970s-soft-rock"],
  ["studio-mastering-1970s-progressive-rock", "1970s-progressive-rock"],
  ["studio-mastering-1980s-new-wave", "1980s-new-wave"],
  ["studio-mastering-1980s-arena-rock", "1980s-arena-rock"],
  ["studio-mastering-1990s-grunge", "1990s-grunge"],
  ["studio-mastering-1990s-britpop", "1990s-britpop"],
  ["studio-mastering-2000s-indie-rock", "2000s-indie-rock"],
  ["studio-mastering-k-pop-dance", "k-pop-dance"],
  ["studio-mastering-chinese-gufeng", "chinese-gufeng"],
  ["studio-mastering-bollywood-pop", "bollywood-pop"],
  ["studio-mastering-indian-classical-fusion", "indian-classical-fusion"],
  ["studio-mastering-flamenco-pop", "flamenco-pop"],
  ["studio-mastering-french-chanson", "french-chanson"],
  ["studio-mastering-reggaeton", "reggaeton"],
  ["studio-mastering-amapiano", "amapiano"],
  ["studio-mastering-arabic-pop", "arabic-pop"],
  ["studio-mastering-full-symphony", "full-symphony"],
  ["studio-mastering-chamber-strings", "chamber-strings"],
  ["studio-mastering-symphonic-rock", "symphonic-rock"],
  ["studio-mastering-neoclassical-minimalism", "neoclassical-minimalism"],
  ["studio-mastering-chicago-blues", "chicago-blues"],
  ["studio-mastering-nashville-country-rock", "nashville-country-rock"],
  ["studio-mastering-gospel-choir", "gospel-choir"],
  ["studio-mastering-beatport-140-deep-dubstep-grime", "beatport-140-deep-dubstep-grime"],
  ["studio-mastering-beatport-afro-house", "beatport-afro-house"],
  ["studio-mastering-beatport-amapiano", "beatport-amapiano"],
  ["studio-mastering-beatport-ambient-experimental", "beatport-ambient-experimental"],
  ["studio-mastering-beatport-bass-club", "beatport-bass-club"],
  ["studio-mastering-beatport-bass-house", "beatport-bass-house"],
  ["studio-mastering-beatport-brazilian-funk", "beatport-brazilian-funk"],
  ["studio-mastering-beatport-breaks-breakbeat-uk-bass", "beatport-breaks-breakbeat-uk-bass"],
  ["studio-mastering-beatport-dance-pop", "beatport-dance-pop"],
  ["studio-mastering-beatport-deep-house-beatport", "beatport-deep-house-beatport"],
  ["studio-mastering-beatport-downtempo", "beatport-downtempo"],
  ["studio-mastering-beatport-drum-and-bass", "beatport-drum-and-bass"],
  ["studio-mastering-beatport-dubstep", "beatport-dubstep"],
  ["studio-mastering-beatport-electro-classic-detroit-modern", "beatport-electro-classic-detroit-modern"],
  ["studio-mastering-beatport-electronica", "beatport-electronica"],
  ["studio-mastering-beatport-funky-house", "beatport-funky-house"],
  ["studio-mastering-beatport-hard-dance-hardcore-neo-rave", "beatport-hard-dance-hardcore-neo-rave"],
  ["studio-mastering-beatport-hard-techno", "beatport-hard-techno"],
  ["studio-mastering-beatport-house", "beatport-house"],
  ["studio-mastering-beatport-indie-dance", "beatport-indie-dance"],
  ["studio-mastering-beatport-tech-house", "beatport-tech-house"],
  ["studio-mastering-beatport-jackin-house", "beatport-jackin-house"],
  ["studio-mastering-beatport-latin-electronic", "beatport-latin-electronic"],
  ["studio-mastering-beatport-mainstage", "beatport-mainstage"],
  ["studio-mastering-beatport-melodic-house-techno", "beatport-melodic-house-techno"],
  ["studio-mastering-beatport-minimal-deep-tech", "beatport-minimal-deep-tech"],
  ["studio-mastering-beatport-nu-disco-disco", "beatport-nu-disco-disco"],
  ["studio-mastering-beatport-organic-house", "beatport-organic-house"],
  ["studio-mastering-beatport-progressive-house", "beatport-progressive-house"],
  ["studio-mastering-beatport-psy-trance", "beatport-psy-trance"],
  ["studio-mastering-beatport-techno-peak-time-driving", "beatport-techno-peak-time-driving"],
  ["studio-mastering-beatport-techno-raw-deep-hypnotic", "beatport-techno-raw-deep-hypnotic"],
  ["studio-mastering-beatport-trance-main-floor", "beatport-trance-main-floor"],
  ["studio-mastering-beatport-trance-raw-deep-hypnotic", "beatport-trance-raw-deep-hypnotic"],
  ["studio-mastering-beatport-trap-future-bass", "beatport-trap-future-bass"],
  ["studio-mastering-beatport-uk-garage-bassline", "beatport-uk-garage-bassline"],
  ["studio-mastering-beatport-african", "beatport-african"],
  ["studio-mastering-beatport-caribbean", "beatport-caribbean"],
  ["studio-mastering-beatport-country", "beatport-country"],
  ["studio-mastering-beatport-dj-edits", "beatport-dj-edits"],
  ["studio-mastering-beatport-hip-hop", "beatport-hip-hop"],
  ["studio-mastering-beatport-latin", "beatport-latin"],
  ["studio-mastering-beatport-pop", "beatport-pop"],
  ["studio-mastering-beatport-r-and-b", "beatport-r-and-b"],
  ["studio-mastering-beatport-rock", "beatport-rock"],
] as const;

export const SUNO_STUDIO_MASTERING_AUDIO_PREVIEWS: readonly SunoStudioMasteringAudioPreview[] =
  SUNO_STUDIO_MASTERING_AUDIO_PREVIEW_ASSETS.map(([key, slug]) => ({
    key,
    audioUrl: `/audio/ai-music-bible/studio-mastering/${slug}.mp3`,
  }));

const AUDIO_PREVIEW_BY_KEY = new Map(
  SUNO_STUDIO_MASTERING_AUDIO_PREVIEWS.map((preview) => [preview.key, preview]),
);

export function getSunoStudioMasteringAudioPreview(key: string) {
  return AUDIO_PREVIEW_BY_KEY.get(key) ?? null;
}
